<?php declare(strict_types=1);require __DIR__.'/bootstrap.php';$pageTitle='UI Kit Playground';$currentPage='design-system';require __DIR__.'/_header.php';?>
<div class="ch-toolbar"><div class="ch-toolbar__title"><span class="ch-badge ch-badge--success">UI KIT 1.0 · CORE</span><h2>CherryHouse bileşenleri</h2><p>Yeni ekranlar canlı sisteme alınmadan önce bu sayfada test edilir.</p></div><div class="ch-toolbar__actions"><button class="ch-button ch-button--secondary" data-ch-open="#demoDrawer">Drawer Aç</button><button class="ch-button ch-button--primary" data-ch-open="#demoModal">Modal Aç</button></div></div>
<section class="ui-kit-grid">
<article class="ch-card"><div class="ch-card__header"><b>CHButton</b><span class="ch-badge ch-badge--success">Hazır</span></div><div class="ch-card__body ui-kit-stack"><button class="ch-button ch-button--primary" data-ch-toast="Değişiklikler kaydedildi">Kaydet</button><button class="ch-button ch-button--secondary">Önizle</button><button class="ch-button ch-button--ghost">Vazgeç</button><button class="ch-button ch-button--success">Etkinleştir</button><button class="ch-button ch-button--danger">Sil</button><button class="ch-button ch-button--primary" disabled>Bekliyor</button></div></article>
<article class="ch-card"><div class="ch-card__header"><b>CHBadge</b></div><div class="ch-card__body ui-kit-stack"><span class="ch-badge ch-badge--success">Etkin</span><span class="ch-badge ch-badge--warning">Yapılandırma gerekli</span><span class="ch-badge ch-badge--danger">Hata</span><span class="ch-badge ch-badge--info">Yayında</span><span class="ch-badge ch-badge--muted">Kapalı</span></div></article>
<article class="ch-card"><div class="ch-card__header"><b>CHForm</b></div><div class="ch-card__body"><div class="ui-kit-form"><label class="ch-field"><span class="ch-label">İşletme adı</span><input class="ch-input" value="CherryHouse"><small class="ch-help">Müşteriye görünen işletme adı.</small></label><label class="ch-field"><span class="ch-label">Paket</span><select class="ch-select"><option>Professional</option><option>Enterprise</option></select></label><label class="ch-field" style="grid-column:1/-1"><span class="ch-label">Açıklama</span><textarea class="ch-textarea">Modern restoran işletim platformu.</textarea></label></div></div></article>
<article class="ch-card"><div class="ch-card__header"><b>Design Tokens</b></div><div class="ch-card__body"><div class="ui-kit-color"><div><i style="background:var(--ch-primary)"></i><small>Primary</small></div><div><i style="background:var(--ch-success)"></i><small>Success</small></div><div><i style="background:var(--ch-warning)"></i><small>Warning</small></div><div><i style="background:var(--ch-danger)"></i><small>Danger</small></div><div><i style="background:var(--ch-info)"></i><small>Info</small></div></div></div></article>
</section>
<section class="ui-kit-section ch-card"><div class="ch-card__header"><div><b>CHTabs ve CHTable</b><div class="ch-help">Listeler ve workspace sekmeleri için ortak standart.</div></div><button class="ch-button ch-button--primary ch-button--sm">+ Yeni Ekle</button></div><div class="ch-card__body"><div class="ch-tabs" style="margin-bottom:16px"><button class="ch-tab is-active" aria-selected="true">Tümü</button><button class="ch-tab">Etkin</button><button class="ch-tab">Kapalı</button></div><div class="ch-table-wrap"><table class="ch-table"><thead><tr><th>Modül</th><th>Paket</th><th>Durum</th><th>İşlem</th></tr></thead><tbody><tr><td><b>QR Menü</b></td><td>Pro</td><td><span class="ch-badge ch-badge--success">Etkin</span></td><td><button class="ch-button ch-button--ghost ch-button--sm">Düzenle</button></td></tr><tr><td><b>KDS</b></td><td>Opsiyonel</td><td><span class="ch-badge ch-badge--muted">Kapalı</span></td><td><button class="ch-button ch-button--ghost ch-button--sm">Düzenle</button></td></tr></tbody></table></div></div></section>
<section class="ui-kit-section ch-empty"><div class="ch-empty__icon">◇</div><h3>CHEmptyState</h3><p>Henüz kayıt yoksa kullanıcıya ne yapacağı açıkça gösterilir.</p><button class="ch-button ch-button--primary">İlk Kaydı Oluştur</button></section>
<div class="ch-overlay" data-ch-overlay hidden></div>
<section class="ch-modal" id="demoModal" hidden><div class="ch-modal__header"><b>CHModal</b><button class="ch-button ch-button--ghost ch-button--icon" data-ch-close>×</button></div><div class="ch-modal__body"><p>Kısa onay ve uyarı işlemleri için standart modal yapısı.</p></div><div class="ch-modal__footer"><button class="ch-button ch-button--ghost" data-ch-close>Vazgeç</button><button class="ch-button ch-button--primary" data-ch-close data-ch-toast="İşlem onaylandı">Onayla</button></div></section>
<aside class="ch-drawer" id="demoDrawer" hidden><div class="ch-drawer__header"><div><b>CHDrawer</b><div class="ch-help">Ekleme ve düzenleme ekranları</div></div><button class="ch-button ch-button--ghost ch-button--icon" data-ch-close>×</button></div><div class="ch-drawer__body"><label class="ch-field"><span class="ch-label">Başlık</span><input class="ch-input" value="Örnek kayıt"></label></div><div class="ch-drawer__footer"><button class="ch-button ch-button--ghost" data-ch-close>Vazgeç</button><button class="ch-button ch-button--primary" data-ch-close data-ch-toast="Drawer kaydedildi">Kaydet</button></div></aside>
<?php require __DIR__.'/_footer.php';?>
