<?php
declare(strict_types=1);
require __DIR__.'/bootstrap.php';
ent_media_upgrade();
$pageTitle='Medya Kütüphanesi';$currentPage='media';$pdo=ent_db();$error='';$notice=trim((string)($_GET['notice']??''));
try{
 if($_SERVER['REQUEST_METHOD']==='POST'){
  ent_verify_csrf();$action=(string)($_POST['action']??'');
  if($action==='upload'){
   $files=$_FILES['media_files']??null;if(!$files||!is_array($files['name']??null))throw new RuntimeException('Yüklenecek görsel seçin.');
   $ok=0;$errors=[];foreach($files['name'] as $i=>$name){if((int)($files['error'][$i]??UPLOAD_ERR_NO_FILE)===UPLOAD_ERR_NO_FILE)continue;try{ent_media_upload(['name'=>$name,'type'=>$files['type'][$i]??'','tmp_name'=>$files['tmp_name'][$i]??'','error'=>$files['error'][$i]??UPLOAD_ERR_NO_FILE,'size'=>$files['size'][$i]??0],(string)($_POST['folder']??'Genel'),(string)($_POST['alt_text']??''));$ok++;}catch(Throwable $e){$errors[]=$name.': '.$e->getMessage();}}
   if(!$ok)throw new RuntimeException(implode(' | ',$errors)?:'Görsel yüklenemedi.');ent_redirect('media.php?notice='.rawurlencode($ok.' görsel yüklendi.'.($errors?' '.count($errors).' dosya atlandı.':'')));
  }
  $ids=array_values(array_filter(array_map('intval',(array)($_POST['ids']??[]))));
  if($action==='bulk_move'&&$ids){$folder=mb_substr(trim((string)($_POST['target_folder']??'Genel')),0,100,'UTF-8')?:'Genel';$marks=implode(',',array_fill(0,count($ids),'?'));$pdo->prepare("UPDATE enterprise_media SET folder=?,updated_at=NOW() WHERE id IN ($marks)")->execute(array_merge([$folder],$ids));ent_redirect('media.php?notice='.rawurlencode(count($ids).' görsel taşındı.'));}
  if($action==='bulk_delete'&&$ids){$deleted=0;$blocked=[];foreach($ids as $id){try{ent_media_delete($id);$deleted++;}catch(Throwable $e){$blocked[]=$e->getMessage();}}ent_redirect('media.php?notice='.rawurlencode($deleted.' görsel silindi.'.($blocked?' '.count($blocked).' kullanılan görsel korunarak atlandı.':'')));}
  if($action==='update'){$id=(int)($_POST['id']??0);$folder=mb_substr(trim((string)($_POST['folder']??'Genel')),0,100,'UTF-8')?:'Genel';$alt=mb_substr(trim((string)($_POST['alt_text']??'')),0,255,'UTF-8');$tags=mb_substr(trim((string)($_POST['tags']??'')),0,500,'UTF-8');$fav=isset($_POST['is_favorite'])?1:0;$pdo->prepare('UPDATE enterprise_media SET folder=?,alt_text=?,tags=?,is_favorite=?,updated_at=NOW() WHERE id=?')->execute([$folder,$alt,$tags,$fav,$id]);ent_redirect('media.php?notice='.rawurlencode('Medya bilgileri güncellendi.'));}
  if($action==='delete'){ent_media_delete((int)($_POST['id']??0));ent_redirect('media.php?notice='.rawurlencode('Görsel silindi.'));}
 }
}catch(Throwable $e){$error=$e->getMessage();}
$q=trim((string)($_GET['q']??''));$folder=trim((string)($_GET['folder']??''));$view=(string)($_GET['view']??'all');$sql='SELECT * FROM enterprise_media WHERE 1=1';$params=[];
if($q!==''){$sql.=' AND (original_name LIKE ? OR alt_text LIKE ? OR tags LIKE ? OR folder LIKE ?)';$like='%'.$q.'%';$params=[$like,$like,$like,$like];}if($folder!==''){$sql.=' AND folder=?';$params[]=$folder;}if($view==='favorites')$sql.=' AND is_favorite=1';$sql.=' ORDER BY is_favorite DESC,id DESC LIMIT 500';$st=$pdo->prepare($sql);$st->execute($params);$items=$st->fetchAll(PDO::FETCH_ASSOC);
$folders=$pdo->query('SELECT folder,COUNT(*) total FROM enterprise_media GROUP BY folder ORDER BY folder')->fetchAll(PDO::FETCH_ASSOC);$total=(int)$pdo->query('SELECT COUNT(*) FROM enterprise_media')->fetchColumn();$bytes=(int)$pdo->query('SELECT COALESCE(SUM(file_size),0) FROM enterprise_media')->fetchColumn();
require __DIR__.'/_header.php';?>
<?php if($error):?><div class="ent-alert danger"><?=ent_e($error)?></div><?php endif;?><?php if($notice):?><div class="ent-alert success"><?=ent_e($notice)?></div><?php endif;?>
<section class="enterprise-hero compact-hero"><div><span>ORTAK GÖRSEL ALTYAPISI</span><h2>Tüm görseller tek merkezde.</h2><p>Ürün, kategori, Hero, logo ve tema görsellerini yükleyin, klasörleyin ve güvenle seçin.</p></div><div class="media-stats"><b><?=$total?><small>Görsel</small></b><b><?=ent_human_bytes($bytes)?><small>Depolama</small></b><b><?=count($folders)?><small>Klasör</small></b></div></section>
<section class="enterprise-panel"><header><div><span>YÜKLEME</span><h3>Çoklu görsel yükle</h3></div></header><form method="post" enctype="multipart/form-data" class="media-upload" data-drop-form><input type="hidden" name="csrf_token" value="<?=ent_e($_SESSION['csrf_token'])?>"><input type="hidden" name="action" value="upload"><label class="media-drop"><input type="file" name="media_files[]" accept="image/jpeg,image/png,image/webp" multiple required><strong>Görselleri sürükleyip bırak</strong><span>JPG, PNG, WebP · dosya başına 8 MB</span></label><div><label>Klasör<input name="folder" value="Ürünler" list="folder-list"></label><label>Ortak alternatif metin<input name="alt_text" placeholder="İsteğe bağlı"></label><button class="primary-action">Yüklemeyi Başlat</button></div></form></section>
<datalist id="folder-list"><?php foreach(['Logo','Hero','Ürünler','Kategoriler','Bannerlar','Temalar','Galeri','Diğer'] as $f):?><option value="<?=$f?>"><?php endforeach;?></datalist>
<section class="library-toolbar"><form method="get"><input type="search" name="q" value="<?=ent_e($q)?>" placeholder="Dosya, etiket veya açıklama ara"><select name="folder"><option value="">Tüm klasörler</option><?php foreach($folders as $f):?><option value="<?=ent_e($f['folder'])?>" <?=$folder===$f['folder']?'selected':''?>><?=ent_e($f['folder'])?> (<?=(int)$f['total']?>)</option><?php endforeach;?></select><select name="view"><option value="all">Tüm görseller</option><option value="favorites" <?=$view==='favorites'?'selected':''?>>Favoriler</option></select><button>Filtrele</button><a href="media.php">Temizle</a></form></section>
<form method="post" id="bulkForm"><input type="hidden" name="csrf_token" value="<?=ent_e($_SESSION['csrf_token'])?>"><div class="bulkbar"><label><input type="checkbox" data-select-all> Tümünü seç</label><span data-selected-count>0 seçili</span><input name="target_folder" list="folder-list" placeholder="Hedef klasör"><button name="action" value="bulk_move">Taşı</button><button class="danger-link" name="action" value="bulk_delete" onclick="return confirm('Seçili ve kullanılmayan görseller silinsin mi?')">Sil</button></div>
<div class="media-grid"><?php foreach($items as $m):$usage=ent_media_usage((string)$m['relative_path']);?><article class="media-card"><label class="media-check"><input type="checkbox" name="ids[]" value="<?=(int)$m['id']?>"></label><div class="media-image"><img src="<?=ent_e(ent_media_url((string)$m['relative_path']))?>" alt="" loading="lazy"><button type="button" data-copy="<?=ent_e($m['relative_path'])?>">Yolu Kopyala</button></div><div class="media-meta"><strong><?=ent_e($m['original_name'])?></strong><span><?=(int)$m['width']?>×<?=(int)$m['height']?> · <?=ent_human_bytes((int)$m['file_size'])?></span><?php if($usage):?><em>Kullanılıyor: <?=ent_e(implode(', ',$usage))?></em><?php else:?><em class="free">Kullanılmıyor</em><?php endif;?></div><details><summary>Düzenle</summary><div class="edit-fields"><label>Klasör<input form="edit-<?=(int)$m['id']?>" name="folder" value="<?=ent_e($m['folder'])?>"></label><label>Alt metin<input form="edit-<?=(int)$m['id']?>" name="alt_text" value="<?=ent_e($m['alt_text'])?>"></label><label>Etiketler<input form="edit-<?=(int)$m['id']?>" name="tags" value="<?=ent_e($m['tags']??'')?>" placeholder="pizza, sıcak, hero"></label><label><input form="edit-<?=(int)$m['id']?>" type="checkbox" name="is_favorite" value="1" <?=!empty($m['is_favorite'])?'checked':''?>> Favori</label><button form="edit-<?=(int)$m['id']?>">Kaydet</button></div></details><form id="edit-<?=(int)$m['id']?>" method="post"><input type="hidden" name="csrf_token" value="<?=ent_e($_SESSION['csrf_token'])?>"><input type="hidden" name="action" value="update"><input type="hidden" name="id" value="<?=(int)$m['id']?>"></form></article><?php endforeach;?><?php if(!$items):?><div class="empty-library">Görsel bulunamadı.</div><?php endif;?></div></form>
<style>
.compact-hero{min-height:auto}.media-stats{display:flex;gap:12px;flex-wrap:wrap}.media-stats b{background:rgba(255,255,255,.09);padding:13px 17px;border-radius:15px;display:grid;font-size:20px}.media-stats small{font-size:10px;opacity:.65}.media-upload{display:grid;grid-template-columns:1.4fr 1fr;gap:16px}.media-drop{min-height:150px;border:2px dashed var(--ent-line);border-radius:18px;display:grid;place-items:center;text-align:center;padding:25px;position:relative}.media-drop input{position:absolute;inset:0;opacity:0;cursor:pointer}.media-drop strong,.media-drop span{display:block}.media-upload>div{display:grid;gap:10px}.media-upload label:not(.media-drop){display:grid;gap:6px;font-weight:700}.media-upload input,.library-toolbar input,.library-toolbar select,.bulkbar input{border:1px solid var(--ent-line);background:var(--ent-surface-2);color:var(--ent-text);border-radius:11px;padding:11px}.library-toolbar{margin:18px 0}.library-toolbar form,.bulkbar{display:flex;gap:9px;align-items:center;flex-wrap:wrap}.library-toolbar a{color:var(--ent-accent)}.bulkbar{position:sticky;top:76px;z-index:10;background:var(--ent-surface);border:1px solid var(--ent-line);padding:10px 13px;border-radius:14px;margin-bottom:14px}.media-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(210px,1fr));gap:14px}.media-card{position:relative;border:1px solid var(--ent-line);background:var(--ent-surface);border-radius:17px;padding:10px}.media-check{position:absolute;z-index:2;top:17px;left:17px;background:var(--ent-surface);padding:5px;border-radius:8px}.media-image{aspect-ratio:1.35;position:relative}.media-image img{width:100%;height:100%;object-fit:cover;border-radius:12px}.media-image button{position:absolute;right:7px;bottom:7px;border:0;border-radius:8px;padding:7px}.media-meta{display:grid;gap:4px;padding:10px 2px}.media-meta strong{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.media-meta span{color:var(--ent-muted);font-size:12px}.media-meta em{font-style:normal;font-size:11px;color:#f59e0b}.media-meta em.free{color:#22c55e}.edit-fields{display:grid;gap:8px;padding-top:8px}.edit-fields label{display:grid;gap:4px;font-size:12px}.edit-fields input{width:100%;padding:8px;border:1px solid var(--ent-line);border-radius:9px;background:var(--ent-surface-2);color:var(--ent-text)}.ent-alert{padding:13px;border-radius:12px;margin-bottom:12px}.ent-alert.success{background:#16a34a22}.ent-alert.danger{background:#ef444422}.empty-library{grid-column:1/-1;padding:35px;text-align:center}@media(max-width:800px){.media-upload{grid-template-columns:1fr}.bulkbar{top:64px}}
</style><script>document.querySelector('[data-select-all]')?.addEventListener('change',e=>document.querySelectorAll('input[name="ids[]"]').forEach(x=>x.checked=e.target.checked));function count(){document.querySelector('[data-selected-count]').textContent=document.querySelectorAll('input[name="ids[]"]:checked').length+' seçili'}document.querySelectorAll('input[name="ids[]"]').forEach(x=>x.addEventListener('change',count));document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{await navigator.clipboard.writeText(b.dataset.copy);b.textContent='Kopyalandı ✓';setTimeout(()=>b.textContent='Yolu Kopyala',1200)});</script>
<?php require __DIR__.'/_footer.php';
