<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/bootstrap.php';
if (!is_file(BASE_PATH.'/storage/installed.lock')) redirect('../install/');
$pdo=db();
if(empty($_SESSION['admin_id']) && (($_SESSION['staff_role']??'')!=='manager')) redirect('./');
if(function_exists('require_permission')) require_permission('catalog.manage');

function mc_scalar(PDO $pdo,string $sql): int { try{return (int)$pdo->query($sql)->fetchColumn();}catch(Throwable){return 0;} }
function mc_rows(PDO $pdo,string $sql): array { try{return $pdo->query($sql)->fetchAll()?:[];}catch(Throwable){return [];} }
$totalProducts=mc_scalar($pdo,'SELECT COUNT(*) FROM products');
$activeProducts=mc_scalar($pdo,'SELECT COUNT(*) FROM products WHERE is_active=1');
$passiveProducts=max(0,$totalProducts-$activeProducts);
$totalCategories=mc_scalar($pdo,'SELECT COUNT(*) FROM categories');
$missingImages=mc_scalar($pdo,"SELECT COUNT(*) FROM products WHERE image_path IS NULL OR image_path=''");
$latest=mc_rows($pdo,'SELECT p.id,p.name,p.price,p.is_active,p.image_path,c.name category_name FROM products p LEFT JOIN categories c ON c.id=p.category_id ORDER BY p.id DESC LIMIT 8');
function mc_money(float $v):string{return number_format($v,2,',','.').' ₺';}
?>
<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Menü Yönetimi Merkezi</title><link rel="stylesheet" href="assets/catalog.css?v=2840"><style>
.hero-grid{display:grid;grid-template-columns:1.35fr .65fr;gap:20px;margin-bottom:20px}.hero-card{background:linear-gradient(135deg,#251516,#421f22);color:#fff;border-radius:24px;padding:28px;box-shadow:0 18px 55px rgba(37,21,22,.18)}.hero-card h2{font-size:30px;margin:8px 0}.hero-card p{max-width:620px;color:rgba(255,255,255,.72)}.quick{display:grid;grid-template-columns:1fr 1fr;gap:12px}.quick a{background:#fff;border:1px solid #eee5e2;border-radius:18px;padding:18px;text-decoration:none;color:#26191a;box-shadow:0 8px 24px rgba(45,25,26,.06)}.quick b{display:block;margin-bottom:5px}.section-title{display:flex;justify-content:space-between;align-items:center;margin:24px 0 12px}.section-title h2{margin:0}.latest-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.product-card{background:#fff;border:1px solid #eee5e2;border-radius:18px;padding:13px}.product-card img,.product-card .noimg{width:100%;aspect-ratio:1.35;object-fit:cover;border-radius:13px;background:#f5efed;display:grid;place-items:center;font-size:28px}.product-card h3{font-size:15px;margin:10px 0 4px}.product-card small{color:#8e7e7b}.product-card .row{display:flex;justify-content:space-between;align-items:center;margin-top:8px}.warning{background:#fff7e8;border:1px solid #f2d59e;border-radius:18px;padding:18px}.warning strong{display:block;font-size:24px;margin-top:4px}@media(max-width:900px){.hero-grid{grid-template-columns:1fr}.latest-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:520px){.quick,.latest-grid{grid-template-columns:1fr}.hero-card{padding:22px}}
</style></head><body><div class="shell"><aside><a class="brand" href="./">🍒 <span>CherryHouse</span></a><nav><a href="./">← Ana Panel</a><a class="active" href="menu-center.php">Menü Merkezi</a><a href="catalog.php?tab=products">Ürünler</a><a href="catalog.php?tab=categories">Kategoriler</a><a href="../" target="_blank">QR Menüyü Aç ↗</a></nav></aside><main>
<header><div><div class="eyebrow">CHERRYHOUSE MENU CENTER</div><h1>Menü Yönetimi</h1><p>QR menü ve POS ürünlerini tek merkezden yönetin.</p></div><a class="primary" href="catalog.php?tab=products">+ Yeni Ürün</a></header>
<div class="stats"><div><small>Toplam ürün</small><b><?=$totalProducts?></b></div><div><small>Aktif ürün</small><b><?=$activeProducts?></b></div><div><small>Pasif ürün</small><b><?=$passiveProducts?></b></div><div><small>Kategori</small><b><?=$totalCategories?></b></div></div>
<div class="hero-grid"><section class="hero-card"><div class="eyebrow">HIZLI MENÜ YÖNETİMİ</div><h2>Menünüz her zaman güncel.</h2><p>Ürünleri, fiyatları, görselleri ve kategorileri yönetin. Kaydettiğiniz değişiklikler aktif ürünlerde doğrudan QR menüye yansır.</p><div style="margin-top:20px;display:flex;gap:10px;flex-wrap:wrap"><a class="primary" href="catalog.php?tab=products">Ürünleri Yönet</a><a class="secondary" href="catalog.php?tab=categories">Kategorileri Yönet</a></div></section><div class="quick"><a href="catalog.php?tab=products"><b>📦 Ürünler</b><small>Düzenle, kopyala, pasife al</small></a><a href="catalog.php?tab=categories"><b>📂 Kategoriler</b><small>Sırala ve görünürlüğü yönet</small></a><a href="../" target="_blank"><b>📱 QR Önizleme</b><small>Müşterinin gördüğü menüyü aç</small></a><div class="warning"><small>Görsel bekleyen ürün</small><strong><?=$missingImages?></strong><a href="catalog.php?tab=products" style="color:#8d5c10">Kontrol et →</a></div></div></div>
<div class="section-title"><h2>Son Eklenen Ürünler</h2><a href="catalog.php?tab=products">Tümünü gör →</a></div><div class="latest-grid"><?php foreach($latest as $p):?><article class="product-card"><?php if(!empty($p['image_path'])):?><img src="../<?=e($p['image_path'])?>" alt=""><?php else:?><div class="noimg">📷</div><?php endif;?><h3><?=e($p['name'])?></h3><small><?=e((string)$p['category_name'])?></small><div class="row"><b><?=mc_money((float)$p['price'])?></b><span class="pill <?=$p['is_active']?'on':'off'?>"><?=$p['is_active']?'Aktif':'Pasif'?></span></div></article><?php endforeach;?><?php if(!$latest):?><div class="panel" style="grid-column:1/-1;padding:25px">Henüz ürün bulunmuyor.</div><?php endif;?></div>
</main></div></body></html>
