<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/bootstrap.php';
if (!is_file(BASE_PATH.'/storage/installed.lock')) redirect('../install/');
if (empty($_SESSION['cashier_id']) && empty($_SESSION['admin_id'])) { http_response_code(403); exit('Bu sayfaya erişim yetkiniz yok.'); }
$pdo=db();$financialOps=new FinancialOperationService($pdo);
$sid=(int)($_GET['session']??0);
$type=in_array((string)($_GET['type']??'bill'),['bill','payment'],true)?(string)$_GET['type']:'bill';
if($sid<1){http_response_code(400);exit('Geçersiz adisyon.');}
$q=$pdo->prepare("SELECT ts.*,t.name table_name,a.name area_name,s.name waiter_name FROM table_sessions ts JOIN restaurant_tables t ON t.id=ts.table_id JOIN dining_areas a ON a.id=t.area_id LEFT JOIN staff_users s ON s.id=ts.opened_by_staff_id WHERE ts.id=? LIMIT 1");
$q->execute([$sid]);$session=$q->fetch();if(!$session){http_response_code(404);exit('Adisyon bulunamadı.');}
$q=$pdo->prepare("SELECT oi.product_name,oi.unit_price,oi.quantity,oi.item_note,oi.status FROM order_items oi JOIN orders o ON o.id=oi.order_id WHERE o.session_id=? AND oi.status<>'cancelled' ORDER BY oi.id");$q->execute([$sid]);$items=$q->fetchAll();
$q=$pdo->prepare("SELECT method,amount,paid_at,note FROM payments WHERE table_session_id=? ORDER BY paid_at,id");$q->execute([$sid]);$payments=$q->fetchAll();
$subtotal=0.0;$complimentaryTotal=0.0;foreach($items as $i){$line=(float)$i['unit_price']*(float)$i['quantity'];if($i['status']==='active')$subtotal+=$line;elseif($i['status']==='complimentary')$complimentaryTotal+=$line;}
$discount=(float)($session['discount_amount']??0);$discountType=(string)($session['discount_type']??'amount');$discountValue=(float)($session['discount_value']??$discount);$total=max(0,$subtotal-$discount);$paid=array_sum(array_map(fn($p)=>(float)$p['amount'],$payments));$remaining=max(0,$total-$paid);
$operations=$financialOps->sessionOperations($sid);
function pmoney(float $v):string{return number_format($v,2,',','.').' ₺';}
function method_label(string $m):string{return ['cash'=>'Nakit','credit_card'=>'Kart','meal_card'=>'Yemek Kartı','transfer'=>'Havale','other'=>'Diğer'][$m]??$m;}
$width=setting('receipt_paper_width','80'); if(!in_array($width,['58','80'],true))$width='80';
$business=setting('business_name','Restoran');$address=setting('receipt_address','');$phone=setting('receipt_phone','');$tax=setting('receipt_tax_info','');$footer=setting('receipt_footer','Afiyet olsun.');$auto=(int)setting('receipt_auto_print','0');
try{$pdo->prepare("INSERT INTO receipt_print_logs(table_session_id,receipt_type,printed_by_type,printed_by_id,printed_at) VALUES(?,?,?,?,NOW())")->execute([$sid,$type,!empty($_SESSION['cashier_id'])?'cashier':'admin',(int)($_SESSION['cashier_id']??$_SESSION['admin_id']??0)]);}catch(Throwable $e){app_log($e);}
?><!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($type==='payment'?'Ödeme Fişi':'Hesap Fişi')?> #<?=$sid?></title><style>
:root{--paper:<?=$width?>mm}*{box-sizing:border-box}body{margin:0;background:#e5e7eb;font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;color:#000}.toolbar{position:sticky;top:0;display:flex;gap:8px;justify-content:center;padding:12px;background:#111827}.toolbar button,.toolbar a{border:0;border-radius:9px;padding:10px 16px;background:#fff;color:#111827;text-decoration:none;font:700 14px system-ui;cursor:pointer}.receipt{width:var(--paper);min-height:100mm;margin:20px auto;background:#fff;padding:5mm 4mm;font-size:12px;line-height:1.35}.center{text-align:center}.title{font-size:18px;font-weight:900}.muted{font-size:10px}.dash{border-top:1px dashed #000;margin:7px 0}.row{display:flex;justify-content:space-between;gap:8px}.item{margin:5px 0}.item .name{font-weight:700}.note{font-size:10px}.total{font-size:15px;font-weight:900}.qr-space{height:8px}@media print{body{background:#fff}.toolbar{display:none}.receipt{margin:0;padding:3mm;width:var(--paper);min-height:0}@page{size:<?=$width?>mm auto;margin:0}}
</style></head><body><div class="toolbar"><button onclick="window.print()">Yazdır</button><a href="../cashier/?session=<?=$sid?>">POS'a Dön</a></div><main class="receipt"><header class="center"><div class="title"><?=e($business)?></div><?php if($address):?><div><?=nl2br(e($address))?></div><?php endif;?><?php if($phone):?><div>Tel: <?=e($phone)?></div><?php endif;?><?php if($tax):?><div class="muted"><?=e($tax)?></div><?php endif;?><div class="dash"></div><strong><?=$type==='payment'?'ÖDEME FİŞİ':'HESAP ÖZETİ'?></strong></header><div class="dash"></div><div class="row"><span>Masa</span><strong><?=e($session['area_name'].' / '.$session['table_name'])?></strong></div><div class="row"><span>Adisyon</span><span>#<?=$sid?></span></div><div class="row"><span>Açılış</span><span><?=e(date('d.m.Y H:i',strtotime((string)$session['opened_at'])))?></span></div><?php if($session['waiter_name']):?><div class="row"><span>Personel</span><span><?=e($session['waiter_name'])?></span></div><?php endif;?><div class="dash"></div><?php foreach($items as $it):?><?php $line=(float)$it['unit_price']*(float)$it['quantity'];?><div class="item"><div class="row"><span class="name"><?=e($it['quantity'])?> × <?=e($it['product_name'])?></span><span><?=pmoney($line)?></span></div><?php if($it['status']==='complimentary'):?><div class="row note"><strong>↳ İKRAM</strong><strong>-<?=pmoney($line)?></strong></div><?php endif;?><?php if($it['item_note']):?><div class="note">↳ <?=e($it['item_note'])?></div><?php endif;?></div><?php endforeach;?><div class="dash"></div><div class="row"><span>Ürünler Toplamı</span><span><?=pmoney($subtotal+$complimentaryTotal)?></span></div><?php if($complimentaryTotal>0):?><div class="row"><span>İkram</span><span>-<?=pmoney($complimentaryTotal)?></span></div><?php endif;?><div class="row"><span>Ara Toplam</span><span><?=pmoney($subtotal)?></span></div><?php if($discount>0):?><div class="row"><span>İskonto<?=$discountType==='percent'?' %'.e(rtrim(rtrim(number_format($discountValue,2,'.',''),'0'),'.')):''?></span><span>-<?=pmoney($discount)?></span></div><?php endif;?><div class="row total"><span>TOPLAM</span><span><?=pmoney($total)?></span></div><?php if($type==='payment'||$paid>0):?><div class="dash"></div><?php foreach($payments as $p):?><div class="row"><span><?=e(method_label((string)$p['method']))?></span><span><?=pmoney((float)$p['amount'])?></span></div><?php endforeach;?><div class="row"><strong>Ödenen</strong><strong><?=pmoney($paid)?></strong></div><div class="row"><strong>Kalan</strong><strong><?=pmoney($remaining)?></strong></div><?php endif;?><div class="dash"></div><footer class="center"><div><?=nl2br(e($footer))?></div><div class="muted"><?=e(date('d.m.Y H:i'))?></div></footer></main><?php if($auto===1):?><script>addEventListener('load',()=>setTimeout(()=>window.print(),250));</script><?php endif;?></body></html>
