<?php
$pageTitle=$pageTitle??'Control Center';$currentPage=$currentPage??'dashboard';$businessName=ent_setting('business_name','CherryHouse');ent_platform_install();
$navigationGroups=ControlCenterRegistry::visibleNavigation();$searchEntries=ControlCenterRegistry::searchableEntries();$quickActions=ControlCenterRegistry::quickActions();$currentNav=ControlCenterRegistry::currentItem($currentPage);$moduleSummary=ControlCenterRegistry::moduleSummary();
?><!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light"><title><?=ent_e($pageTitle)?> · <?=ent_e($businessName)?></title>
<link rel="stylesheet" href="assets/media-picker.css?v=3036"><link rel="stylesheet" href="assets/enterprise.css?v=3073"><link rel="stylesheet" href="assets/admin-ui.css?v=3073"><link rel="stylesheet" href="assets/cherry-ui.css?v=3073"><link rel="stylesheet" href="assets/control-center.css?v=3073"><link rel="stylesheet" href="assets/dashboard-engine.css?v=3073"><link rel="stylesheet" href="assets/navigation-engine.css?v=3073"><link rel="stylesheet" href="assets/sidebar-accordion-repair.css?v=30731"><link rel="stylesheet" href="assets/menu-workspace.css?v=3074"><link rel="stylesheet" href="assets/menu-workspace-ui.css?v=30751"><link rel="stylesheet" href="assets/control-center-consistency.css?v=30752"><link rel="stylesheet" href="assets/ui-kit-core.css?v=3081"><link rel="stylesheet" href="assets/cherry-design-system.css?v=100"><?php if(in_array($currentPage,['staff','permissions'],true)):?><link rel="stylesheet" href="assets/personnel-workspace.css?v=3082"><?php endif;?></head>
<body class="ent-ui ch-ui" data-page="<?=ent_e($currentPage)?>"><div class="ch-shell" data-admin-shell>
<aside class="ch-sidebar" data-admin-sidebar><div class="ch-brand"><a href="./"><span class="ch-brand-mark">CH</span><div><strong><?=ent_e($businessName)?></strong><small>Control Center</small></div></a><button type="button" data-sidebar-collapse aria-label="Menüyü daralt">‹</button></div>
<button class="ch-command" type="button" data-command-open><span>⌕</span><b>Hızlı ara</b><kbd>⌘K</kbd></button>
<nav class="ch-nav" aria-label="Yönetim menüsü"><?php foreach($navigationGroups as $group):$expanded=($currentNav['group_id']??'')===$group['id'];?><section class="ch-nav-group<?=$expanded?' is-current':''?>" data-nav-group data-group-id="<?=ent_e($group['id'])?>"><button class="ch-nav-group-title" type="button" data-nav-group-toggle aria-expanded="<?=$expanded?'true':'false'?>"><span><?=ent_e($group['group'])?></span><i>⌄</i></button><div class="ch-nav-items"><?php foreach($group['items'] as $item):?><a class="<?=$currentPage===$item['id']?'active':''?>" href="<?=ent_e($item['href'])?>" <?=!empty($item['external'])?'target="_blank" rel="noopener"':''?> data-nav-item><span class="ch-nav-icon"><?=ent_e($item['icon'])?></span><b><?=ent_e($item['label'])?></b></a><?php endforeach;?></div></section><?php endforeach;?></nav>
<div class="ch-sidebar-footer"><div><i></i><span><?=$moduleSummary['active']?> / <?=$moduleSummary['total']?> modül aktif</span></div><small>v30.8.1 · UI Kit Core</small></div></aside>
<div class="ch-backdrop" data-sidebar-backdrop></div><div class="ch-main"><header class="ch-topbar"><div class="ch-topbar-left"><button class="ch-icon-button ch-mobile-menu" type="button" data-sidebar-toggle>☰</button><div class="ch-breadcrumb"><small><a href="./">GENEL BAKIŞ</a><?php if($currentNav && $currentPage!=='dashboard'):?> <i>›</i> <?=ent_e(mb_strtoupper((string)$currentNav['group_label'],'UTF-8'))?><?php endif;?></small><h1><?=ent_e($pageTitle)?></h1></div></div><div class="ch-topbar-actions"><button class="ch-search-button" type="button" data-command-open><span>⌕</span><b>Her yerde ara</b><kbd>⌘K</kbd></button><details class="ch-quick-menu"><summary class="ch-quick-trigger"><span>＋</span><b>Hızlı İşlem</b><i>⌄</i></summary><div class="ch-quick-panel"><header><strong>Hızlı İşlemler</strong><small>Sık kullanılan işlemlere ulaşın</small></header><?php foreach($quickActions as $action):?><a href="<?=ent_e($action['href'])?>"><span><?=ent_e($action['icon'])?></span><div><b><?=ent_e($action['label'])?></b><small><?=ent_e($action['keywords'][0]??'')?></small></div></a><?php endforeach;?></div></details><button class="ch-icon-button" type="button" title="Bildirimler">♢</button><details class="ch-profile"><summary><span><?=ent_e(mb_substr($businessName,0,1,'UTF-8'))?></span><div><b>Yönetici</b><small>Control Center</small></div><i>⌄</i></summary><div><a href="../?page=profile">Hesabım</a><a href="../logout.php">Çıkış</a></div></details></div></header><main class="ch-content">
<div class="command-palette" data-command-palette hidden><button class="command-backdrop" type="button" data-command-close></button><section><header><span>⌕</span><input type="search" data-command-input placeholder="Sayfa veya işlem ara…" autocomplete="off"><kbd>ESC</kbd></header><div class="command-meta"><span data-command-count><?=count($searchEntries)?> sonuç</span><small>↑↓ gezin · Enter aç</small></div><div class="command-results" data-command-results><?php foreach($searchEntries as $entry):?><a href="<?=ent_e($entry['href'])?>" data-command-item data-search="<?=ent_e($entry['search'])?>"><span><?=ent_e($entry['icon'])?></span><div><b><?=ent_e($entry['label'])?></b><small><?=ent_e($entry['group_label'])?> · <?=ent_e($entry['kind'])?></small></div><em>↵</em></a><?php endforeach;?><div class="command-empty" data-command-empty hidden><b>Sonuç bulunamadı</b><small>Farklı bir kelime deneyin.</small></div></div></section></div>
