<?php
declare(strict_types=1);
require __DIR__.'/bootstrap.php';
$pageTitle='Kategori Yönetimi';$currentPage='categories';$pdo=ent_db();$notice=trim((string)($_GET['notice']??''));$error='';
$cols=ent_columns('categories');$hasActive=in_array('is_active',$cols,true);$hasSort=in_array('sort_order',$cols,true);
try{if($_SERVER['REQUEST_METHOD']==='POST'){ent_verify_csrf();$action=(string)($_POST['action']??'');if($action==='save_category'){$id=(int)($_POST['id']??0);$name=trim((string)($_POST['name']??''));$description=trim((string)($_POST['description']??''));$imagePath=ltrim(trim((string)($_POST['image_path']??'')),'/');$sort=(int)($_POST['sort_order']??0);$active=isset($_POST['is_active'])?1:0;if($name==='')throw new RuntimeException('Kategori adı zorunludur.');$sets=['name=?','description=?'];$vals=[$name,$description];if($hasSort){$sets[]='sort_order=?';$vals[]=$sort;}if($hasActive){$sets[]='is_active=?';$vals[]=$active;}if($id>0){$vals[]=$id;$pdo->prepare('UPDATE categories SET '.implode(',',$sets).' WHERE id=?')->execute($vals);ent_redirect('categories.php?notice='.rawurlencode('Kategori güncellendi.'));}$fields=['name','description'];$vals=[$name,$description];if($hasSort){$fields[]='sort_order';$vals[]=$sort;}if($hasActive){$fields[]='is_active';$vals[]=$active;}$pdo->prepare('INSERT INTO categories('.implode(',',$fields).') VALUES('.implode(',',array_fill(0,count($fields),'?')).')')->execute($vals);ent_redirect('categories.php?notice='.rawurlencode('Kategori eklendi.'));}if($action==='toggle_category'&&$hasActive){$pdo->prepare('UPDATE categories SET is_active=IF(is_active=1,0,1) WHERE id=?')->execute([(int)$_POST['id']]);ent_redirect('categories.php?notice='.rawurlencode('Kategori durumu güncellendi.'));}}}catch(Throwable $e){$error=$e->getMessage();}
$editId=max(0,(int)($_GET['edit']??0));$edit=['id'=>0,'name'=>'','description'=>'','sort_order'=>0,'is_active'=>1];if($editId){$q=$pdo->prepare('SELECT * FROM categories WHERE id=?');$q->execute([$editId]);if($r=$q->fetch(PDO::FETCH_ASSOC))$edit=array_merge($edit,$r);}
$sql='SELECT c.*,COUNT(p.id) product_count FROM categories c LEFT JOIN products p ON p.category_id=c.id GROUP BY c.id ORDER BY '.($hasSort?'c.sort_order,':'').'c.id';$categories=$pdo->query($sql)->fetchAll(PDO::FETCH_ASSOC);
require __DIR__.'/_header.php';
?>

<?php if($notice):?><div class="ch-flash ch-flash--success"><?=ent_e($notice)?></div><?php endif;?><?php if($error):?><div class="ch-flash ch-flash--danger"><?=ent_e($error)?></div><?php endif;?>
<section class="mw-page"><header class="mw-page-head"><div><span class="ch-eyebrow">MENÜ YÖNETİMİ</span><h2>Kategoriler</h2><p>Kategorileri kart görünümünde yönetin ve sıralama merkezine hızlıca erişin.</p></div><div class="mw-head-actions"><a class="ch-btn ch-btn--ghost" href="reorder.php">Sıralamayı Yönet</a><a class="ch-btn ch-btn--primary" href="categories.php?action=create">＋ Yeni Kategori</a></div></header><nav class="ch-workspace-tabs"><a href="menu.php">Genel Bakış</a><a href="products.php">Ürünler</a><a class="active" href="categories.php">Kategoriler</a><a href="variants.php">Varyantlar</a><a href="media.php">Medya Merkezi</a></nav><section class="mw-category-grid"><?php foreach($categories as $c):?><article class="ch-card mw-category-card"><header><div class="mw-category-order"><?=str_pad((string)(int)($c['sort_order']??0),2,'0',STR_PAD_LEFT)?></div><span class="ch-badge <?=(!$hasActive||!empty($c['is_active']))?'ch-badge--success':'ch-badge--muted'?>"><?=(!$hasActive||!empty($c['is_active']))?'Aktif':'Pasif'?></span></header><div><h3><?=ent_e($c['name'])?></h3><p><?=ent_e((string)($c['description']?:'Açıklama eklenmemiş.'))?></p></div><footer><span><b><?=(int)$c['product_count']?></b> ürün</span><div><a class="ch-icon-action" href="categories.php?edit=<?=(int)$c['id']?>">✎</a><?php if($hasActive):?><form method="post"><input type="hidden" name="csrf_token" value="<?=ent_e($_SESSION['csrf_token'])?>"><input type="hidden" name="action" value="toggle_category"><input type="hidden" name="id" value="<?=(int)$c['id']?>"><button class="ch-icon-action"><?=!empty($c['is_active'])?'◉':'○'?></button></form><?php endif;?></div></footer></article><?php endforeach;?><?php if(!$categories):?><div class="ch-empty ch-card"><b>Henüz kategori yok.</b><a class="ch-btn ch-btn--primary" href="categories.php?action=create">İlk kategoriyi oluştur</a></div><?php endif;?></section></section>
<?php $drawerOpen=$editId>0||($_GET['action']??'')==='create';if($drawerOpen):?><div class="mw-drawer-backdrop"><aside class="mw-drawer mw-drawer--small"><header><div><span class="ch-eyebrow"><?=$editId?'KATEGORİYİ DÜZENLE':'YENİ KATEGORİ'?></span><h3><?=$editId?ent_e((string)$edit['name']):'Kategori oluştur'?></h3></div><a class="ch-icon-action" href="categories.php">×</a></header><form method="post" class="mw-editor"><input type="hidden" name="csrf_token" value="<?=ent_e($_SESSION['csrf_token'])?>"><input type="hidden" name="action" value="save_category"><input type="hidden" name="id" value="<?=(int)$edit['id']?>"><section class="mw-editor-panel active"><div class="mw-field-grid"><label class="span-2">Kategori adı<input name="name" value="<?=ent_e($edit['name'])?>" required></label><label class="span-2">Açıklama<textarea name="description" rows="5"><?=ent_e($edit['description'])?></textarea></label><?php if($hasSort):?><label>Sıralama<input type="number" name="sort_order" value="<?=(int)$edit['sort_order']?>"></label><?php endif;?></div><?php if($hasActive):?><label class="mw-switch"><input type="checkbox" name="is_active" value="1" <?=!empty($edit['is_active'])?'checked':''?>><span><b>Aktif kategori</b><small>Menüde görünür</small></span></label><?php endif;?></section><footer><a class="ch-btn ch-btn--ghost" href="categories.php">Vazgeç</a><button class="ch-btn ch-btn--primary"><?=$editId?'Kaydet':'Kategori Oluştur'?></button></footer></form></aside></div><?php endif;?>
<?php require __DIR__.'/_footer.php';?>
