<?php
declare(strict_types=1);
require __DIR__.'/bootstrap.php';require_once dirname(__DIR__,2).'/app/permissions.php';require_permission('permissions.manage');
$pageTitle='Roller ve Yetkiler';$currentPage='permissions';$pdo=ent_db();$roles=['manager','cashier','waiter'];$catalog=permission_catalog();$notice='';$error='';$defaults=function_exists('default_role_permissions')?default_role_permissions():[];
try{if($_SERVER['REQUEST_METHOD']==='POST'){ent_verify_csrf();$role=(string)($_POST['role']??'');if(!in_array($role,$roles,true))throw new RuntimeException('Geçersiz rol.');$selected=array_values(array_intersect(array_keys($catalog),(array)($_POST['permissions']??[])));$pdo->beginTransaction();$q=$pdo->prepare('INSERT INTO role_permissions(role_key,permission_key,is_allowed,updated_by,updated_at) VALUES(?,?,?,?,NOW()) ON DUPLICATE KEY UPDATE is_allowed=VALUES(is_allowed),updated_by=VALUES(updated_by),updated_at=NOW()');foreach(array_keys($catalog) as $perm)$q->execute([$role,$perm,in_array($perm,$selected,true)?1:0,(int)($_SESSION['admin_id']??0)]);$pdo->commit();if(function_exists('audit_log'))audit_log('role_permissions_updated','Rol yetkileri güncellendi.',['role'=>$role]);$notice=pw_role_label($role).' yetkileri kaydedildi.';}}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$error=$e->getMessage();}
$current=[];try{foreach($pdo->query('SELECT role_key,permission_key,is_allowed FROM role_permissions') as $r)$current[$r['role_key']][$r['permission_key']]=(bool)$r['is_allowed'];}catch(Throwable){}
function pw_role_label(string $role):string{return $role==='manager'?'Yönetici':($role==='cashier'?'Kasiyer':'Garson');}
require __DIR__.'/_header.php';?>
<?php if($notice):?><div class="ch-alert ch-alert--success"><?=ent_e($notice)?></div><?php endif;?><?php if($error):?><div class="ch-alert ch-alert--danger"><?=ent_e($error)?></div><?php endif;?>
<section class="pw-page"><div class="ch-toolbar"><div><span class="ch-eyebrow">YÖNETİM WORKSPACE</span><h2>Roller ve Yetkiler</h2><p>Her rolün görebileceği ekranları ve yapabileceği kritik işlemleri yönetin.</p></div><div class="ch-toolbar__actions"><a class="ch-button ch-button--secondary" href="personnel.php">Personellere Dön</a></div></div><nav class="ch-tabs"><a href="personnel.php">Personeller</a><a class="is-active" href="permissions.php">Roller ve Yetkiler</a></nav><div class="ch-alert ch-alert--warning"><b>Güvenlik notu:</b> Tam yetkili sistem yöneticileri çekirdek güvenlik kuralları gereği kritik erişimlerini korur.</div><div class="pw-role-grid"><?php foreach($roles as $role):?><form class="ch-card pw-role-card" method="post"><input type="hidden" name="csrf_token" value="<?=ent_e($_SESSION['csrf_token'])?>"><input type="hidden" name="role" value="<?=ent_e($role)?>"><header><span class="pw-role-icon"><?=$role==='manager'?'◆':($role==='cashier'?'₺':'♨')?></span><div><h3><?=ent_e(pw_role_label($role))?></h3><p><?=$role==='manager'?'Yönetim ve raporlama':($role==='cashier'?'Kasa ve tahsilat':'Masa ve sipariş')?></p></div></header><div class="pw-permissions"><?php foreach($catalog as $key=>$label):$checked=$current[$role][$key]??in_array($key,$defaults[$role]??[],true);?><label><input type="checkbox" name="permissions[]" value="<?=ent_e($key)?>" <?=$checked?'checked':''?>><span><b><?=ent_e($label)?></b><small><?=ent_e($key)?></small></span></label><?php endforeach;?></div><footer><button class="ch-button ch-button--primary ch-button--block">Yetkileri Kaydet</button></footer></form><?php endforeach;?></div></section><?php require __DIR__.'/_footer.php';?>
