<?php
declare(strict_types=1);
require __DIR__.'/bootstrap.php';
require_permission('staff.manage');
$pageTitle='Personel Yönetimi';$currentPage='staff';$pdo=ent_db();$notice=trim((string)($_GET['notice']??''));$error='';
function pw_role_label(string $role): string{return $role==='manager'?'Yönetici':($role==='cashier'?'Kasiyer':'Garson');}
try{
 if($_SERVER['REQUEST_METHOD']==='POST'){
  ent_verify_csrf();$action=(string)($_POST['action']??'');$id=(int)($_POST['id']??0);
  if($action==='add_staff'){
   $name=trim((string)($_POST['name']??''));$username=strtolower(trim((string)($_POST['username']??'')));$pin=preg_replace('/\D+/','',(string)($_POST['pin']??''));$role=in_array((string)($_POST['role']??''),['waiter','cashier','manager'],true)?(string)$_POST['role']:'waiter';
   if($name===''||!preg_match('/^[a-z0-9._-]{3,100}$/',$username))throw new RuntimeException('Ad soyad ve en az 3 karakterlik kullanıcı adı zorunludur.');if(strlen($pin)!==4)throw new RuntimeException('PIN tam olarak 4 rakam olmalıdır.');
   $q=$pdo->prepare('SELECT COUNT(*) FROM staff_users WHERE username=? AND deleted_at IS NULL');$q->execute([$username]);if((int)$q->fetchColumn()>0)throw new RuntimeException('Bu kullanıcı adı zaten kullanılıyor.');
   $password=bin2hex(random_bytes(8));$pdo->prepare('INSERT INTO staff_users(name,username,password_hash,pin_hash,pin_enabled,role,is_active) VALUES(?,?,?,?,1,?,1)')->execute([$name,$username,password_hash($password,PASSWORD_DEFAULT),password_hash($pin,PASSWORD_DEFAULT),$role]);
   if(function_exists('audit_log'))audit_log('staff_created','Personel hesabı oluşturuldu.',['staff_id'=>(int)$pdo->lastInsertId(),'role'=>$role]);ent_redirect('personnel.php?notice='.rawurlencode('Personel hesabı oluşturuldu.'));
  }
  if($id<1)throw new RuntimeException('Geçersiz personel.');
  if($action==='set_pin'){$pin=preg_replace('/\D+/','',(string)($_POST['pin']??''));if(strlen($pin)!==4)throw new RuntimeException('PIN tam olarak 4 rakam olmalıdır.');$pdo->prepare('UPDATE staff_users SET pin_hash=?,pin_enabled=1 WHERE id=?')->execute([password_hash($pin,PASSWORD_DEFAULT),$id]);ent_redirect('personnel.php?notice='.rawurlencode('PIN kodu güncellendi.'));}
  if($action==='disable_pin'){$pdo->prepare('UPDATE staff_users SET pin_hash=NULL,pin_enabled=0 WHERE id=?')->execute([$id]);ent_redirect('personnel.php?notice='.rawurlencode('PIN girişi kapatıldı.'));}
  if($action==='toggle'){$pdo->prepare('UPDATE staff_users SET is_active=IF(is_active=1,0,1) WHERE id=?')->execute([$id]);ent_redirect('personnel.php?notice='.rawurlencode('Personel durumu güncellendi.'));}
  if($action==='delete'){$used=0;foreach([['table_sessions','opened_by_staff_id'],['orders','staff_id'],['payments','staff_id']] as $ref){if(!ent_table_exists($ref[0])||!in_array($ref[1],ent_columns($ref[0]),true))continue;$q=$pdo->prepare('SELECT COUNT(*) FROM '.$ref[0].' WHERE '.$ref[1].'=?');$q->execute([$id]);$used+=(int)$q->fetchColumn();}if(ent_table_exists('cash_sessions')){$cols=ent_columns('cash_sessions');if(in_array('opened_by_staff_id',$cols,true)&&in_array('closed_by_staff_id',$cols,true)){$q=$pdo->prepare('SELECT COUNT(*) FROM cash_sessions WHERE opened_by_staff_id=? OR closed_by_staff_id=?');$q->execute([$id,$id]);$used+=(int)$q->fetchColumn();}}
   if($used===0){$pdo->prepare('DELETE FROM staff_users WHERE id=?')->execute([$id]);$msg='Personel kalıcı olarak silindi.';}else{$pdo->prepare("UPDATE staff_users SET is_active=0,pin_enabled=0,pin_hash=NULL,deleted_at=NOW(),username=CONCAT('deleted_',id,'_',UNIX_TIMESTAMP()) WHERE id=?")->execute([$id]);$msg='Personel işlem geçmişi korunarak arşivlendi.';}if(function_exists('audit_log'))audit_log('staff_deleted',$msg,['staff_id'=>$id,'history_count'=>$used]);ent_redirect('personnel.php?notice='.rawurlencode($msg));}
 }
}catch(Throwable $e){$error=$e->getMessage();}
$search=trim((string)($_GET['q']??''));$roleFilter=trim((string)($_GET['role']??''));$statusFilter=trim((string)($_GET['status']??''));$where=['deleted_at IS NULL'];$params=[];
if($search!==''){$where[]='(name LIKE ? OR username LIKE ?)';$params[]='%'.$search.'%';$params[]='%'.$search.'%';}if(in_array($roleFilter,['waiter','cashier','manager'],true)){$where[]='role=?';$params[]=$roleFilter;}if($statusFilter==='active')$where[]='is_active=1';elseif($statusFilter==='passive')$where[]='is_active=0';
$q=$pdo->prepare('SELECT id,name,username,role,is_active,pin_enabled,last_login_at FROM staff_users WHERE '.implode(' AND ',$where).' ORDER BY is_active DESC,role,name');$q->execute($params);$staff=$q->fetchAll(PDO::FETCH_ASSOC);
$all=$pdo->query('SELECT role,is_active,COUNT(*) c FROM staff_users WHERE deleted_at IS NULL GROUP BY role,is_active')->fetchAll(PDO::FETCH_ASSOC);$stats=['total'=>0,'active'=>0,'waiter'=>0,'cashier'=>0,'manager'=>0];foreach($all as $r){$c=(int)$r['c'];$stats['total']+=$c;if((int)$r['is_active'])$stats['active']+=$c;if(isset($stats[$r['role']]))$stats[$r['role']]+=$c;}
require __DIR__.'/_header.php';
?>
<?php if($notice):?><div class="ch-alert ch-alert--success"><?=ent_e($notice)?></div><?php endif;?><?php if($error):?><div class="ch-alert ch-alert--danger"><?=ent_e($error)?></div><?php endif;?>
<section class="pw-page"><div class="ch-toolbar"><div><span class="ch-eyebrow">YÖNETİM WORKSPACE</span><h2>Personel Merkezi</h2><p>Personel hesapları, roller ve PIN erişimlerini tek merkezden yönetin.</p></div><div class="ch-toolbar__actions"><a class="ch-button ch-button--secondary" href="permissions.php">Roller ve Yetkiler</a><a class="ch-button ch-button--primary" href="personnel.php?action=create">＋ Yeni Personel</a></div></div>
<nav class="ch-tabs"><a class="is-active" href="personnel.php">Personeller</a><a href="permissions.php">Roller ve Yetkiler</a></nav>
<div class="pw-stats"><article class="ch-card"><small>Toplam Personel</small><strong><?=$stats['total']?></strong></article><article class="ch-card"><small>Aktif</small><strong><?=$stats['active']?></strong></article><article class="ch-card"><small>Garson</small><strong><?=$stats['waiter']?></strong></article><article class="ch-card"><small>Kasiyer</small><strong><?=$stats['cashier']?></strong></article><article class="ch-card"><small>Yönetici</small><strong><?=$stats['manager']?></strong></article></div>
<section class="ch-card pw-list"><form class="pw-filter" method="get"><label class="ch-field pw-search"><span>⌕</span><input type="search" name="q" value="<?=ent_e($search)?>" placeholder="Ad veya kullanıcı adı ara"></label><label class="ch-field"><select name="role"><option value="">Tüm roller</option><option value="waiter" <?=$roleFilter==='waiter'?'selected':''?>>Garson</option><option value="cashier" <?=$roleFilter==='cashier'?'selected':''?>>Kasiyer</option><option value="manager" <?=$roleFilter==='manager'?'selected':''?>>Yönetici</option></select></label><label class="ch-field"><select name="status"><option value="">Tüm durumlar</option><option value="active" <?=$statusFilter==='active'?'selected':''?>>Aktif</option><option value="passive" <?=$statusFilter==='passive'?'selected':''?>>Pasif</option></select></label><button class="ch-button ch-button--secondary">Filtrele</button><?php if($search!==''||$roleFilter!==''||$statusFilter!==''):?><a class="ch-button ch-button--ghost" href="personnel.php">Temizle</a><?php endif;?></form>
<div class="ch-table-wrap"><table class="ch-table"><thead><tr><th>Personel</th><th>Rol</th><th>PIN</th><th>Son Giriş</th><th>Durum</th><th class="pw-right">İşlemler</th></tr></thead><tbody><?php foreach($staff as $u):?><tr><td><div class="pw-person"><span><?=ent_e(mb_substr($u['name'],0,1,'UTF-8'))?></span><div><b><?=ent_e($u['name'])?></b><small>@<?=ent_e($u['username'])?></small></div></div></td><td><span class="ch-badge ch-badge--info"><?=ent_e(pw_role_label($u['role']))?></span></td><td><span class="ch-badge <?=$u['pin_enabled']?'ch-badge--success':'ch-badge--muted'?>"><?=$u['pin_enabled']?'Etkin':'Kapalı'?></span></td><td><?=!empty($u['last_login_at'])?ent_e(date('d.m.Y H:i',strtotime($u['last_login_at']))):'<span class="pw-muted">Henüz giriş yok</span>'?></td><td><span class="ch-badge <?=$u['is_active']?'ch-badge--success':'ch-badge--muted'?>"><?=$u['is_active']?'Aktif':'Pasif'?></span></td><td><div class="pw-actions"><button class="ch-button ch-button--ghost ch-button--sm" type="button" data-pin-open data-id="<?=$u['id']?>" data-name="<?=ent_e($u['name'])?>">PIN</button><form method="post"><input type="hidden" name="csrf_token" value="<?=ent_e($_SESSION['csrf_token'])?>"><input type="hidden" name="action" value="toggle"><input type="hidden" name="id" value="<?=$u['id']?>"><button class="ch-button ch-button--secondary ch-button--sm"><?=$u['is_active']?'Pasifleştir':'Aktifleştir'?></button></form><form method="post" onsubmit="return confirm('Bu personeli silmek istediğinize emin misiniz?')"><input type="hidden" name="csrf_token" value="<?=ent_e($_SESSION['csrf_token'])?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=$u['id']?>"><button class="ch-button ch-button--danger ch-button--sm">Sil</button></form></div></td></tr><?php endforeach;?><?php if(!$staff):?><tr><td colspan="6"><div class="ch-empty-state"><b>Personel bulunamadı</b><small>Filtreleri temizleyin veya yeni personel oluşturun.</small></div></td></tr><?php endif;?></tbody></table></div></section></section>
<?php if(($_GET['action']??'')==='create'):?><div class="ch-drawer-backdrop is-open"><aside class="ch-drawer is-open"><header class="ch-drawer__header"><div><span class="ch-eyebrow">YENİ KAYIT</span><h3>Yeni Personel</h3></div><a class="ch-button ch-button--ghost ch-button--icon" href="personnel.php">×</a></header><form method="post" class="ch-drawer__body pw-form"><input type="hidden" name="csrf_token" value="<?=ent_e($_SESSION['csrf_token'])?>"><input type="hidden" name="action" value="add_staff"><label class="ch-field"><span>Ad soyad</span><input name="name" required maxlength="190"></label><label class="ch-field"><span>Kullanıcı adı</span><input name="username" pattern="[a-zA-Z0-9._-]{3,100}" required></label><label class="ch-field"><span>4 haneli PIN</span><input name="pin" inputmode="numeric" pattern="[0-9]{4}" maxlength="4" required></label><label class="ch-field"><span>Rol</span><select name="role"><option value="waiter">Garson</option><option value="cashier">Kasiyer</option><option value="manager">Yönetici personel</option></select></label><footer class="ch-drawer__footer"><a class="ch-button ch-button--ghost" href="personnel.php">Vazgeç</a><button class="ch-button ch-button--primary">Personel Oluştur</button></footer></form></aside></div><?php endif;?>
<div class="ch-modal" data-pin-modal hidden><button class="ch-modal__backdrop" type="button" data-pin-close></button><section class="ch-modal__dialog"><header><div><span class="ch-eyebrow">ERİŞİM</span><h3 data-pin-title>PIN Güncelle</h3></div><button class="ch-button ch-button--ghost ch-button--icon" type="button" data-pin-close>×</button></header><form method="post"><input type="hidden" name="csrf_token" value="<?=ent_e($_SESSION['csrf_token'])?>"><input type="hidden" name="action" value="set_pin"><input type="hidden" name="id" data-pin-id><label class="ch-field"><span>Yeni 4 haneli PIN</span><input name="pin" inputmode="numeric" pattern="[0-9]{4}" maxlength="4" required></label><footer><button class="ch-button ch-button--ghost" type="button" data-pin-close>Vazgeç</button><button class="ch-button ch-button--primary">PIN’i Kaydet</button></footer></form></section></div>
<?php require __DIR__.'/_footer.php';?>
