<?php
declare(strict_types=1);
$root=dirname(__DIR__,2);$done=false;$messages=[];$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 try{
  $backup=$root.'/storage/backups/v30.0.0-'.date('Ymd-His');if(!is_dir($backup)&&!mkdir($backup,0775,true))throw new RuntimeException('Yedek klasörü oluşturulamadı.');
  $files=['app/assets/cherry-design/tokens.css','app/assets/cherry-design/base.css','app/assets/cherry-design/components.css','app/assets/cherry-design/compat.css','app/assets/cherry-design/design-system.js','admin/enterprise/_header.php'];
  foreach($files as $rel){$src=__DIR__.'/files/'.$rel;$dst=$root.'/'.$rel;if(is_file($dst)){@mkdir($backup.'/'.dirname($rel),0775,true);copy($dst,$backup.'/'.$rel);}@mkdir(dirname($dst),0775,true);if(!copy($src,$dst))throw new RuntimeException($rel.' kopyalanamadı.');$messages[]='Yüklendi: '.$rel;}
  foreach(['staff/index.php','cashier/index.php'] as $rel){$dst=$root.'/'.$rel;if(!is_file($dst))continue;$raw=file_get_contents($dst);$original=$raw;$css='<link rel="stylesheet" href="../app/assets/cherry-design/tokens.css?v=3000"><link rel="stylesheet" href="../app/assets/cherry-design/compat.css?v=3000"><script defer src="../app/assets/cherry-design/design-system.js?v=3000"></script>';
   if(!str_contains($raw,'cherry-design/tokens.css')){$raw=str_replace('</head>',$css.'</head>',$raw,$count);if(!$count)throw new RuntimeException($rel.' head etiketi bulunamadı.');copy($dst,$backup.'/'.$rel);file_put_contents($dst,$raw,LOCK_EX);$messages[]='Uyumluluk katmanı eklendi: '.$rel;}else{$messages[]='Zaten güncel: '.$rel;}}
  $release=$root.'/app/release.php';if(is_file($release)){copy($release,$backup.'/app-release.php');$r=file_get_contents($release);$r=preg_replace("/'version'\\s*=>\\s*'[^']*'/","'version' => '30.0.0'",$r,1);file_put_contents($release,$r,LOCK_EX);}
  if(function_exists('opcache_reset'))@opcache_reset();$done=true;
 }catch(Throwable $e){$error=$e->getMessage();}
}
?><!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>CherryHouse v30.0.0</title><style>body{font:16px system-ui;background:#f5f3ef;color:#211c19;margin:0;display:grid;place-items:center;min-height:100vh}.box{width:min(720px,calc(100% - 32px));background:white;border:1px solid #e4dfd9;border-radius:24px;padding:32px;box-shadow:0 20px 60px #211c1915}h1{margin-top:0}button,a{display:inline-flex;padding:13px 18px;border-radius:12px;border:0;background:#b4233f;color:white;text-decoration:none;font-weight:800}.ok{background:#eaf8f1;color:#126746;padding:14px;border-radius:12px}.err{background:#fff0f2;color:#a91f35;padding:14px;border-radius:12px}li{margin:6px 0;color:#625d57}</style></head><body><main class="box"><small>CHERRYHOUSE FOUNDATION UI</small><h1>v30.0.0 Design System</h1><p>Ortak renk, tipografi, buton, kart, form, modal, toast ve dokunmatik uyumluluk altyapısını kurar.</p><?php if($error):?><p class="err"><?=htmlspecialchars($error)?></p><?php elseif($done):?><p class="ok">Güncelleme başarıyla tamamlandı.</p><ul><?php foreach($messages as $m):?><li><?=htmlspecialchars($m)?></li><?php endforeach;?></ul><a href="../../admin/enterprise/">Enterprise Paneli Aç</a><?php else:?><form method="post"><button>Güncellemeyi Uygula</button></form><?php endif;?></main></body></html>
