<?php
declare(strict_types=1);require __DIR__.'/bootstrap.php';
$notice='';$error='';
$themes=QrThemeRegistry::all();
if($_SERVER['REQUEST_METHOD']==='POST'){
 try{
  verify_csrf();
  $allowedSections=array_column(QrExperience::sections(),'key');$order=[];
  foreach(explode(',',(string)($_POST['qr_section_order']??'')) as $key){$key=trim($key);if(in_array($key,$allowedSections,true)&&!in_array($key,$order,true))$order[]=$key;}
  foreach($allowedSections as $key)if(!in_array($key,$order,true))$order[]=$key;
  $values=[
   'qr_theme'=>qrs_choice((string)($_POST['qr_theme']??'cherry'),array_keys($themes),'cherry'),
   'qr_accent_color'=>qrs_hex((string)($_POST['qr_accent_color']??''),'#8b1e2d'),
   'qr_ui_background'=>qrs_hex((string)($_POST['qr_ui_background']??''),'#f4efe6'),
   'qr_ui_surface'=>qrs_hex((string)($_POST['qr_ui_surface']??''),'#fffdf8'),
   'qr_ui_text'=>qrs_hex((string)($_POST['qr_ui_text']??''),'#191814'),
   'qr_ui_muted'=>qrs_hex((string)($_POST['qr_ui_muted']??''),'#716c63'),
   'qr_font_family'=>qrs_choice((string)($_POST['qr_font_family']??'inter'),['inter','manrope','poppins','playfair','cormorant','dm-sans'],'inter'),
   'qr_card_style'=>qrs_choice((string)($_POST['qr_card_style']??'elevated'),['elevated','bordered','flat','editorial'],'elevated'),
   'qr_card_radius'=>(string)max(0,min(36,(int)($_POST['qr_card_radius']??16))),
   'qr_ui_category_style'=>qrs_choice((string)($_POST['qr_ui_category_style']??'pastel'),['pastel','minimal','accent'],'pastel'),
   'qr_ui_product_density'=>qrs_choice((string)($_POST['qr_ui_product_density']??'compact'),['compact','comfortable'],'compact'),
   'qr_hero_title'=>trim((string)($_POST['qr_hero_title']??'')),
   'qr_hero_subtitle'=>trim((string)($_POST['qr_hero_subtitle']??'')),
   'qr_hero_image'=>trim((string)($_POST['qr_hero_image']??'')),
   'qr_logo_image'=>trim((string)($_POST['qr_logo_image']??'')),
   'qr_hero_height'=>(string)max(45,min(100,(int)($_POST['qr_hero_height']??78))),
   'qr_hero_overlay'=>(string)max(0,min(90,(int)($_POST['qr_hero_overlay']??35))),
   'qr_show_hero'=>qrs_bool('qr_show_hero'),'qr_show_status'=>qrs_bool('qr_show_status'),'qr_show_readonly_note'=>qrs_bool('qr_show_readonly_note'),
   'qr_show_search'=>qrs_bool('qr_show_search'),'qr_ui_first_category_open'=>qrs_bool('qr_ui_first_category_open'),'qr_ui_single_category'=>qrs_bool('qr_ui_single_category'),'qr_ui_show_category_count'=>qrs_bool('qr_ui_show_category_count'),'qr_ui_show_category_numbers'=>qrs_bool('qr_ui_show_category_numbers'),'qr_ui_show_row_arrow'=>qrs_bool('qr_ui_show_row_arrow'),'qr_ui_show_product_images'=>qrs_bool('qr_ui_show_product_images'),'qr_ui_show_descriptions'=>qrs_bool('qr_ui_show_descriptions'),
   'qr_detail_variant'=>qrs_choice((string)($_POST['qr_detail_variant']??'sheet'),['sheet','centered','fullscreen'],'sheet'),'qr_detail_image_height'=>(string)max(180,min(620,(int)($_POST['qr_detail_image_height']??360))),'qr_ui_detail_note'=>trim((string)($_POST['qr_ui_detail_note']??'')),
   'qr_show_promo_bar'=>qrs_bool('qr_show_promo_bar'),'qr_promo_text'=>trim((string)($_POST['qr_promo_text']??'')),'qr_show_featured'=>qrs_bool('qr_show_featured'),'qr_feature_title'=>trim((string)($_POST['qr_feature_title']??'')),'qr_feature_text'=>trim((string)($_POST['qr_feature_text']??'')),'qr_show_chef_note'=>qrs_bool('qr_show_chef_note'),'qr_chef_note_title'=>trim((string)($_POST['qr_chef_note_title']??'')),'qr_chef_note_text'=>trim((string)($_POST['qr_chef_note_text']??'')),'qr_show_story'=>qrs_bool('qr_show_story'),'qr_story_title'=>trim((string)($_POST['qr_story_title']??'')),'qr_story_text'=>trim((string)($_POST['qr_story_text']??'')),'qr_show_social'=>qrs_bool('qr_show_social'),'qr_social_title'=>trim((string)($_POST['qr_social_title']??'')),'qr_social_text'=>trim((string)($_POST['qr_social_text']??'')),'qr_price_note'=>trim((string)($_POST['qr_price_note']??'')),
   'qr_section_order'=>implode(',',$order),'qr_section_categories_enabled'=>'1'
  ];
  qrs_save($values);audit_log('qr_studio_published','QR Studio ayarları canlı olarak kaydedildi.',['count'=>count($values)]);$notice='Değişiklikler kaydedildi ve canlı QR menüye yayınlandı.';
 }catch(Throwable $e){$error=$e->getMessage();}
}
$sections=QrExperience::sections();$order=QrExperience::sectionOrder();usort($sections,fn($a,$b)=>array_search($a['key'],$order,true)<=>array_search($b['key'],$order,true));
function checkedSetting(string $k,string $d='1'): string{return qrs_get($k,$d)==='1'?'checked':'';}
?><!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>QR Experience Studio</title><link rel="stylesheet" href="assets/studio.css?v=2920"></head><body>
<div class="studio-shell"><aside class="side"><a class="brand" href="./"><b>✦ QR Experience</b><small>Studio v29.2</small></a><nav><button class="active" data-tab="design">Tasarım</button><button data-tab="hero">Hero</button><button data-tab="menu">Menü görünümü</button><button data-tab="components">Bileşenler</button><button data-tab="layout">Sayfa düzeni</button></nav><div class="side-links"><a href="../">← Yönetim paneli</a><a href="../../" target="_blank">Canlı menüyü aç ↗</a></div></aside>
<main class="main"><header class="top"><div><span>CHERRYHOUSE</span><h1>QR Experience Studio</h1><p>Değişiklikleri anlık izle, tek düğmeyle kaydet ve yayınla.</p></div><div class="publish-state" id="saveState">Canlı sürüm</div></header>
<?php if($notice):?><div class="alert ok"><?=qrs_e($notice)?></div><?php endif;?><?php if($error):?><div class="alert err"><?=qrs_e($error)?></div><?php endif;?>
<form method="post" id="studioForm"><input type="hidden" name="csrf" value="<?=qrs_e(csrf_token())?>"><input type="hidden" name="qr_section_order" id="sectionOrder" value="<?=qrs_e(implode(',',$order))?>">
<div class="workspace"><div class="controls">
<section class="tab active" data-pane="design"><h2>Tasarım sistemi</h2><p>Tema, renk, tipografi ve kart biçimini tek yerden yönetin.</p><div class="theme-grid"><?php foreach($themes as $key=>$theme):?><label class="theme-card"><input type="radio" name="qr_theme" value="<?=qrs_e($key)?>" <?=qrs_get('qr_theme','cherry')===$key?'checked':''?>><b><?=qrs_e($theme['name'])?></b><small><?=qrs_e($theme['description'])?></small></label><?php endforeach;?></div><div class="grid two"><div class="panel"><h3>Renkler</h3><?php foreach(['qr_ui_background'=>'Sayfa','qr_ui_surface'=>'Kart','qr_ui_text'=>'Ana yazı','qr_ui_muted'=>'İkincil yazı','qr_accent_color'=>'Vurgu'] as $k=>$label):?><label class="color"><input type="color" name="<?=$k?>" value="<?=qrs_e(qrs_get($k,['qr_ui_background'=>'#f4efe6','qr_ui_surface'=>'#fffdf8','qr_ui_text'=>'#191814','qr_ui_muted'=>'#716c63','qr_accent_color'=>'#8b1e2d'][$k]))?>"><span><?=$label?></span></label><?php endforeach;?></div><div class="panel"><h3>Tipografi ve kart</h3><label>Yazı tipi<select name="qr_font_family"><?php foreach(['inter'=>'Inter','manrope'=>'Manrope','poppins'=>'Poppins','playfair'=>'Playfair Display','cormorant'=>'Cormorant Garamond','dm-sans'=>'DM Sans'] as $v=>$l):?><option value="<?=$v?>" <?=qrs_get('qr_font_family','inter')===$v?'selected':''?>><?=$l?></option><?php endforeach;?></select></label><label>Kart biçimi<select name="qr_card_style"><?php foreach(['elevated'=>'Yükseltilmiş','bordered'=>'Çerçeveli','flat'=>'Düz','editorial'=>'Editoryal'] as $v=>$l):?><option value="<?=$v?>" <?=qrs_get('qr_card_style','elevated')===$v?'selected':''?>><?=$l?></option><?php endforeach;?></select></label><label>Köşe yuvarlaklığı <output data-out="qr_card_radius"><?=qrs_e(qrs_get('qr_card_radius','16'))?> px</output><input type="range" name="qr_card_radius" min="0" max="36" value="<?=qrs_e(qrs_get('qr_card_radius','16'))?>"></label></div></div></section>
<section class="tab" data-pane="hero"><h2>Hero alanı</h2><div class="panel"><div class="grid two"><label>Başlık<input name="qr_hero_title" value="<?=qrs_e(qrs_get('qr_hero_title','İyi yemek, mutlu anlar.'))?>"></label><label>Alt başlık<input name="qr_hero_subtitle" value="<?=qrs_e(qrs_get('qr_hero_subtitle','Taze malzemelerle hazırlanmış lezzetleri keşfedin.'))?>"></label><label>Kapak görseli<input name="qr_hero_image" value="<?=qrs_e(qrs_get('qr_hero_image'))?>"></label><label>Logo görseli<input name="qr_logo_image" value="<?=qrs_e(qrs_get('qr_logo_image'))?>"></label></div><label>Hero yüksekliği <output data-out="qr_hero_height"><?=qrs_e(qrs_get('qr_hero_height','78'))?>%</output><input type="range" name="qr_hero_height" min="45" max="100" value="<?=qrs_e(qrs_get('qr_hero_height','78'))?>"></label><label>Karartma <output data-out="qr_hero_overlay"><?=qrs_e(qrs_get('qr_hero_overlay','35'))?>%</output><input type="range" name="qr_hero_overlay" min="0" max="90" value="<?=qrs_e(qrs_get('qr_hero_overlay','35'))?>"></label><div class="toggles"><?php foreach(['qr_show_hero'=>'Hero açık','qr_show_status'=>'Açık durumu','qr_show_readonly_note'=>'Bilgilendirme notu'] as $k=>$l):?><label class="switch"><input type="checkbox" name="<?=$k?>" <?=checkedSetting($k)?>><span></span><b><?=$l?></b></label><?php endforeach;?></div></div></section>
<section class="tab" data-pane="menu"><h2>Menü görünümü</h2><div class="grid two"><div class="panel"><h3>Kategori davranışı</h3><label>Kategori stili<select name="qr_ui_category_style"><?php foreach(['pastel'=>'Pastel','minimal'=>'Minimal','accent'=>'Vurgulu'] as $v=>$l):?><option value="<?=$v?>" <?=qrs_get('qr_ui_category_style','pastel')===$v?'selected':''?>><?=$l?></option><?php endforeach;?></select></label><?php foreach(['qr_show_search'=>'Arama alanı','qr_ui_first_category_open'=>'İlk kategori açık','qr_ui_single_category'=>'Tek kategori açık','qr_ui_show_category_count'=>'Ürün sayısı','qr_ui_show_category_numbers'=>'Kategori numarası'] as $k=>$l):?><label class="switch"><input type="checkbox" name="<?=$k?>" <?=checkedSetting($k,$k==='qr_ui_first_category_open'?'0':'1')?>><span></span><b><?=$l?></b></label><?php endforeach;?></div><div class="panel"><h3>Ürün kartları</h3><label>Yoğunluk<select name="qr_ui_product_density"><option value="compact" <?=qrs_get('qr_ui_product_density','compact')==='compact'?'selected':''?>>Kompakt</option><option value="comfortable" <?=qrs_get('qr_ui_product_density')==='comfortable'?'selected':''?>>Rahat</option></select></label><?php foreach(['qr_ui_show_product_images'=>'Ürün görselleri','qr_ui_show_descriptions'=>'Açıklamalar','qr_ui_show_row_arrow'=>'Detay oku'] as $k=>$l):?><label class="switch"><input type="checkbox" name="<?=$k?>" <?=checkedSetting($k)?>><span></span><b><?=$l?></b></label><?php endforeach;?><label>Detay görünümü<select name="qr_detail_variant"><option value="sheet" <?=qrs_get('qr_detail_variant','sheet')==='sheet'?'selected':''?>>Alt panel</option><option value="centered" <?=qrs_get('qr_detail_variant')==='centered'?'selected':''?>>Ortalanmış</option><option value="fullscreen" <?=qrs_get('qr_detail_variant')==='fullscreen'?'selected':''?>>Tam ekran</option></select></label><label>Detay görsel yüksekliği<input type="number" min="180" max="620" name="qr_detail_image_height" value="<?=qrs_e(qrs_get('qr_detail_image_height','360'))?>"></label><label>Detay notu<textarea name="qr_ui_detail_note"><?=qrs_e(qrs_get('qr_ui_detail_note','İçerik ve alerjen bilgileri için personelimize danışabilirsiniz.'))?></textarea></label></div></div></section>
<section class="tab" data-pane="components"><h2>Bileşenler</h2><div class="grid two"><div class="panel"><label class="switch"><input type="checkbox" name="qr_show_promo_bar" <?=checkedSetting('qr_show_promo_bar')?>><span></span><b>Kampanya bandı</b></label><label>Metin<input name="qr_promo_text" value="<?=qrs_e(qrs_get('qr_promo_text','Bugüne özel fırsatları keşfet ✦'))?>"></label><label class="switch"><input type="checkbox" name="qr_show_featured" <?=checkedSetting('qr_show_featured')?>><span></span><b>Öne çıkan alan</b></label><label>Başlık<input name="qr_feature_title" value="<?=qrs_e(qrs_get('qr_feature_title','Günün öne çıkan lezzeti'))?>"></label><label>Açıklama<textarea name="qr_feature_text"><?=qrs_e(qrs_get('qr_feature_text','Öne çıkan lezzetlerimizi keşfet.'))?></textarea></label></div><div class="panel"><label class="switch"><input type="checkbox" name="qr_show_chef_note" <?=checkedSetting('qr_show_chef_note','0')?>><span></span><b>Şef notu</b></label><label>Başlık<input name="qr_chef_note_title" value="<?=qrs_e(qrs_get('qr_chef_note_title','Mevsimin en iyi ürünleriyle'))?>"></label><label>Metin<textarea name="qr_chef_note_text"><?=qrs_e(qrs_get('qr_chef_note_text','Mutfağımızda her tabak günlük hazırlanır.'))?></textarea></label><label class="switch"><input type="checkbox" name="qr_show_story" <?=checkedSetting('qr_show_story','0')?>><span></span><b>Hikâyemiz</b></label><label>Başlık<input name="qr_story_title" value="<?=qrs_e(qrs_get('qr_story_title','Sofrada başlayan bir hikâye'))?>"></label><label>Metin<textarea name="qr_story_text"><?=qrs_e(qrs_get('qr_story_text','Lezzeti ve iyi malzemeyi merkeze alan bir mutfak.'))?></textarea></label><label class="switch"><input type="checkbox" name="qr_show_social" <?=checkedSetting('qr_show_social','0')?>><span></span><b>Sosyal alan</b></label><label>Başlık<input name="qr_social_title" value="<?=qrs_e(qrs_get('qr_social_title','Bizi Instagram’da takip et'))?>"></label><label>Metin<textarea name="qr_social_text"><?=qrs_e(qrs_get('qr_social_text','Yeni ürünler ve duyurular için sosyal hesaplarımızdayız.'))?></textarea></label><label>Fiyat notu<input name="qr_price_note" value="<?=qrs_e(qrs_get('qr_price_note','Fiyatlarımıza KDV dahildir.'))?>"></label></div></div></section>
<section class="tab" data-pane="layout"><h2>Sayfa düzeni</h2><p>Bölümleri tutup sürükleyin. Kategoriler her zaman açık kalır.</p><div class="layout-list" id="layoutList"><?php foreach($sections as $i=>$section):?><article draggable="true" data-key="<?=qrs_e($section['key'])?>"><span class="grab">☰</span><div><b><?=qrs_e($section['label'])?></b><small><?=qrs_e($section['description'])?></small></div><em><?=str_pad((string)($i+1),2,'0',STR_PAD_LEFT)?></em></article><?php endforeach;?></div></section>
</div><aside class="preview"><div class="preview-head"><div><b>Canlı önizleme</b><small>Kaydetmeden önce görün</small></div><button type="button" id="refreshPreview">↻</button></div><div class="phone"><iframe id="previewFrame" src="../../?preview=studio&v=<?=time()?>"></iframe></div></aside></div>
<div class="savebar"><span id="dirtyText">Tüm değişiklikler canlı sürümle aynı.</span><button type="submit">Kaydet ve Yayınla</button></div></form></main></div><script src="assets/studio.js?v=2920"></script></body></html>
