<?php
$pageTitle = $pageTitle ?? 'Control Center';
$currentPage = $currentPage ?? 'dashboard';
$businessName = ent_setting('business_name', 'CherryHouse');
ent_platform_install();
$enterpriseNotifications = ent_notifications(6);
$unreadNotificationCount = count(array_filter($enterpriseNotifications, static fn($n) => (int)($n['is_read'] ?? 0) === 0));
$navigationGroups = ControlCenterRegistry::visibleNavigation();
$menuItems=[]; foreach($navigationGroups as $g){foreach($g['items'] as $i)$menuItems[]=$i;}
$activeModules=count(array_filter(modules()->all(),static fn($m)=>!empty($m['enabled'])));
?><!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light"><title><?=ent_e($pageTitle)?> · <?=ent_e($businessName)?></title>
<link rel="stylesheet" href="assets/enterprise.css?v=3070"><link rel="stylesheet" href="assets/admin-ui.css?v=3070"><link rel="stylesheet" href="assets/control-center.css?v=3070"><link rel="stylesheet" href="assets/media-picker.css?v=2930"><link rel="stylesheet" href="../assets/ch-media-library.css?v=3033"></head>
<body class="ent-ui" data-page="<?=ent_e($currentPage)?>"><div class="enterprise-shell" data-admin-shell>
<aside class="enterprise-sidebar" data-admin-sidebar><div class="sidebar-head"><a class="enterprise-brand" href="./"><span>CH</span><div><strong><?=ent_e($businessName)?></strong><small>Control Center</small></div></a><button class="sidebar-collapse" type="button" data-sidebar-collapse aria-label="Menüyü daralt">⇤</button></div>
<button class="command-trigger" type="button" data-command-open><span>⌕</span><b>Hızlı ara</b><kbd>⌘ K</kbd></button>
<nav class="enterprise-nav" aria-label="Yönetim menüsü">
<?php foreach($navigationGroups as $group):?><small class="nav-label"><?=ent_e(mb_strtoupper((string)$group['group'],'UTF-8'))?></small><?php foreach($group['items'] as $item):?>
<a class="<?=$currentPage===$item['id']?'active':''?>" href="<?=ent_e($item['href'])?>" <?=!empty($item['external'])?'target="_blank" rel="noopener"':''?> data-nav-item data-keywords="<?=ent_e($item['keywords']??$item['label'])?>"><span><?=ent_e($item['icon'])?></span><b><?=ent_e($item['label'])?></b><button type="button" class="favorite-toggle" data-favorite="<?=ent_e($item['id'])?>" aria-label="Favoriye ekle">☆</button></a>
<?php endforeach;endforeach;?></nav><div class="sidebar-spacer"></div><div class="enterprise-version"><strong>Control Center v1.0</strong><span><?=$activeModules?> aktif modül · v30.7.0</span></div></aside>
<div class="sidebar-backdrop" data-sidebar-backdrop></div><div class="enterprise-main"><header class="enterprise-topbar"><button class="mobile-menu" type="button" data-sidebar-toggle aria-label="Menüyü aç">☰</button><div class="page-heading"><small>CHERRYHOUSE CONTROL CENTER</small><h1><?=ent_e($pageTitle)?></h1></div><div class="topbar-actions"><span class="cc-module-pill"><i></i><?=$activeModules?> modül aktif</span><button class="icon-button" type="button" data-command-open aria-label="Hızlı ara">⌕</button><button class="icon-button" type="button" data-theme-toggle aria-label="Tema değiştir">◐</button>
<details class="notification-menu" data-notification-menu><summary class="icon-button" aria-label="Bildirimler">♢<?php if($unreadNotificationCount>0):?><i></i><em><?=$unreadNotificationCount?></em><?php endif;?></summary><div class="notification-panel"><header><strong>Bildirim Merkezi</strong><span><?=$unreadNotificationCount?> okunmamış</span></header><div data-notification-list><?php if($enterpriseNotifications):foreach($enterpriseNotifications as $n):?><a href="<?=ent_e($n['target_url']?:'./')?>" class="notification-item <?=((int)$n['is_read']===0)?'unread':''?>" data-notification-id="<?=(int)$n['id']?>"><b><?=ent_e($n['title'])?></b><span><?=ent_e($n['message'])?></span><small><?=ent_e(date('d.m H:i',strtotime((string)$n['created_at'])))?></small></a><?php endforeach;else:?><p class="notification-empty">Yeni bildirim yok.</p><?php endif;?></div></div></details>
<?php if(module_enabled('qr-menu',true)):?><a class="preview-button" href="../../" target="_blank" rel="noopener">Canlı Menü <span>↗</span></a><?php endif;?></div></header><main class="enterprise-content">
<div class="command-palette" data-command-palette hidden><button class="command-backdrop" type="button" data-command-close aria-label="Aramayı kapat"></button><section role="dialog" aria-modal="true"><header><span>⌕</span><input type="search" data-command-input placeholder="Menü veya işlem ara…" autocomplete="off"><kbd>ESC</kbd></header><div class="command-results" data-command-results><div class="command-section-label">SAYFALAR VE İŞLEMLER</div><?php foreach($menuItems as $item):?><a href="<?=ent_e($item['href'])?>" data-command-item data-search="<?=ent_e(mb_strtolower($item['label'].' '.($item['keywords']??''),'UTF-8'))?>"><span><?=ent_e($item['icon'])?></span><div><b><?=ent_e($item['label'])?></b><small><?=ent_e($item['href'])?></small></div><em>↗</em></a><?php endforeach;?></div><footer><span>↑↓ Gezin</span><span>Enter Aç</span><span>Esc Kapat</span></footer></section></div>
