<?php
declare(strict_types=1);
require dirname(__DIR__,2).'/app/bootstrap.php';
require_once dirname(__DIR__,2).'/app/qr/QrExperience.php';
if(!is_file(BASE_PATH.'/storage/installed.lock')) redirect('../../install/');if(!QrExperience::adminAllowed()) redirect('../');$notice='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){try{verify_csrf();$allowed=array_column(QrExperience::sections(),'key');$order=[];foreach(explode(',',(string)($_POST['qr_section_order']??'')) as $k){$k=trim($k);if(in_array($k,$allowed,true)&&!in_array($k,$order,true))$order[]=$k;}foreach($allowed as $k)if(!in_array($k,$order,true))$order[]=$k;$q=db()->prepare('INSERT INTO settings(setting_key,setting_value) VALUES(?,?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value)');$q->execute(['qr_section_order',implode(',',$order)]);foreach($allowed as $k)$q->execute(['qr_section_'.$k.'_enabled',isset($_POST['enabled_'.$k])?'1':'0']);audit_log('qr_layout_updated','QR Experience bölüm sırası güncellendi.');$notice='Sayfa düzeni kaydedildi.';}catch(Throwable $e){$error=$e->getMessage();}}
require __DIR__.'/_layout.php';qrx_start('Sayfa Düzeni','layout');$map=[];foreach(QrExperience::sections() as $s)$map[$s['key']]=$s;
?>
<div class="qrx-title"><div><h1>Sayfa Düzeni</h1><p>Bölümleri sürükleyerek sırala ve görünürlüğünü yönet.</p></div></div><?php if($notice):?><div class="qrx-notice"><?=e($notice)?></div><?php endif;?><?php if($error):?><div class="qrx-notice qrx-error"><?=e($error)?></div><?php endif;?>
<div class="qrx-studio"><form class="qrx-panel" method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" id="qr_section_order" name="qr_section_order" value="<?=e(implode(',',QrExperience::sectionOrder()))?>"><div style="padding:22px"><h2 style="margin-top:0">Ana menü bölümleri</h2><ul class="qrx-sortable" id="qrx-sortable"><?php foreach(QrExperience::sectionOrder() as $key):$s=$map[$key];?><li data-key="<?=e($key)?>"><span class="qrx-handle">☰</span><div><strong><?=e($s['label'])?></strong><small><?=e($s['description'])?></small></div><label><input type="checkbox" name="enabled_<?=e($key)?>" <?=QrExperience::enabled($key,$key==='chef_note'||$key==='story'||$key==='social'?'0':'1')?'checked':''?>> Açık</label></li><?php endforeach;?></ul></div><div class="qrx-actions"><button class="qrx-btn">Düzeni Kaydet</button></div></form><aside class="qrx-preview-wrap"><div class="qrx-phone"><iframe id="qrx-preview" src="../../?preview=1"></iframe></div></aside></div>
<?php qrx_end();
