<?php
declare(strict_types=1);
require_once __DIR__.'/../../app/bootstrap.php';require_once __DIR__.'/../../app/Modules/QRExperience/helpers.php';qrx_require_admin();$pdo=db();$message='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(isset($_POST['delete_id'])){$pdo->prepare('DELETE FROM qr_product_badges WHERE id=?')->execute([(int)$_POST['delete_id']]);$message='Rozet silindi.';}
 else{$pdo->prepare('INSERT INTO qr_product_badges(product_id,label,color,is_active,updated_at) VALUES(?,?,?,?,NOW())')->execute([(int)$_POST['product_id'],trim((string)$_POST['label']),$_POST['color'],isset($_POST['is_active'])?1:0]);$message='Rozet eklendi.';}
}
$products=$pdo->query('SELECT id,name FROM products ORDER BY name')->fetchAll(PDO::FETCH_ASSOC);$rows=qrx_badges($pdo);
?><!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Ürün Rozetleri</title><link rel="stylesheet" href="assets/studio.css"></head><body class="page"><header class="simple"><a href="index.php">← Dashboard</a><h1>Ürün Rozetleri</h1><p>Yeni, vegan, acılı veya şef önerisi gibi rozetler ekle.</p></header><main class="component-grid"><?php if($message):?><div class="notice"><?=$message?></div><?php endif;?><section class="panel"><form method="post" class="stack"><label>Ürün<select name="product_id" required><?php foreach($products as $p):?><option value="<?=$p['id']?>"><?=htmlspecialchars($p['name'])?></option><?php endforeach;?></select></label><label>Rozet<input name="label" required placeholder="Şef Önerisi"></label><label>Renk<input type="color" name="color" value="#d71920"></label><label><input type="checkbox" name="is_active" checked> Aktif</label><button>Ekle</button></form></section><section class="panel"><h2>Mevcut Rozetler</h2><?php foreach($rows as $r):?><div class="campaign-row"><span><i class="badge-dot" style="background:<?=htmlspecialchars($r['color'])?>"></i><b><?=htmlspecialchars($r['label'])?></b><small><?=htmlspecialchars($r['product_name']??'Silinmiş ürün')?></small></span><form method="post"><button class="danger" name="delete_id" value="<?=$r['id']?>">Sil</button></form></div><?php endforeach;?></section></main></body></html>
