<?php
$pageTitle=$pageTitle??'Control Center';$currentPage=$currentPage??'dashboard';$businessName=ent_setting('business_name','CherryHouse');ent_platform_install();
$navigationGroups=ControlCenterRegistry::visibleNavigation();$menuItems=[];foreach($navigationGroups as $g){foreach($g['items'] as $i)$menuItems[]=$i;}
$activeModules=count(array_filter(modules()->all(),static fn($m)=>!empty($m['enabled'])));
?><!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light"><title><?=ent_e($pageTitle)?> · <?=ent_e($businessName)?></title>
<link rel="stylesheet" href="assets/enterprise.css?v=3072"><link rel="stylesheet" href="assets/admin-ui.css?v=3072"><link rel="stylesheet" href="assets/cherry-ui.css?v=3072"><link rel="stylesheet" href="assets/control-center.css?v=3072"><link rel="stylesheet" href="assets/dashboard-engine.css?v=3072"></head>
<body class="ent-ui ch-ui" data-page="<?=ent_e($currentPage)?>"><div class="ch-shell" data-admin-shell>
<aside class="ch-sidebar" data-admin-sidebar><div class="ch-brand"><a href="./"><span class="ch-brand-mark">CH</span><div><strong><?=ent_e($businessName)?></strong><small>Control Center</small></div></a><button type="button" data-sidebar-collapse aria-label="Menüyü daralt">‹</button></div>
<button class="ch-command" type="button" data-command-open><span>⌕</span><b>Hızlı ara</b><kbd>⌘K</kbd></button>
<nav class="ch-nav" aria-label="Yönetim menüsü"><?php foreach($navigationGroups as $group):$gid='g-'.md5($group['group']);?><section class="ch-nav-group" data-nav-group><button class="ch-nav-group-title" type="button" data-nav-group-toggle aria-expanded="true"><span><?=ent_e($group['group'])?></span><i>⌄</i></button><div class="ch-nav-items" id="<?=$gid?>"><?php foreach($group['items'] as $item):?><a class="<?=$currentPage===$item['id']?'active':''?>" href="<?=ent_e($item['href'])?>" <?=!empty($item['external'])?'target="_blank" rel="noopener"':''?> data-nav-item><span class="ch-nav-icon"><?=ent_e($item['icon'])?></span><b><?=ent_e($item['label'])?></b></a><?php endforeach;?></div></section><?php endforeach;?></nav>
<div class="ch-sidebar-footer"><div><i></i><span><?=$activeModules?> aktif modül</span></div><small>v30.7.2 · Dashboard Engine</small></div></aside>
<div class="ch-backdrop" data-sidebar-backdrop></div><div class="ch-main"><header class="ch-topbar"><div class="ch-topbar-left"><button class="ch-icon-button ch-mobile-menu" type="button" data-sidebar-toggle>☰</button><div class="ch-breadcrumb"><small>CHERRYHOUSE</small><h1><?=ent_e($pageTitle)?></h1></div></div><div class="ch-topbar-actions"><button class="ch-search-button" type="button" data-command-open><span>⌕</span><b>Her yerde ara</b><kbd>⌘K</kbd></button><a class="ch-icon-button" href="design-system.php" title="UI Kit">✦</a><button class="ch-icon-button" type="button" title="Bildirimler">♢</button><details class="ch-profile"><summary><span><?=ent_e(mb_substr($businessName,0,1,'UTF-8'))?></span><div><b>Yönetici</b><small>Control Center</small></div><i>⌄</i></summary><div><a href="../?page=profile">Hesabım</a><a href="../logout.php">Çıkış</a></div></details></div></header><main class="ch-content">
<div class="command-palette" data-command-palette hidden><button class="command-backdrop" type="button" data-command-close></button><section><header><span>⌕</span><input type="search" data-command-input placeholder="Menü veya işlem ara…"><kbd>ESC</kbd></header><div class="command-results" data-command-results><?php foreach($menuItems as $item):?><a href="<?=ent_e($item['href'])?>" data-command-item data-search="<?=ent_e(mb_strtolower($item['label'],'UTF-8'))?>"><span><?=ent_e($item['icon'])?></span><div><b><?=ent_e($item['label'])?></b><small><?=ent_e($item['href'])?></small></div></a><?php endforeach;?></div></section></div>
