<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/bootstrap.php';
// v28.0.1 güvenli yükleyici: eski/önbellekte kalmış bootstrap durumunda sınıfı doğrudan yükle.
if (!class_exists('BusinessDayService', false)) {
    $serviceFile = dirname(__DIR__).'/app/Core/BusinessDayService.php';
    if (is_file($serviceFile)) require_once $serviceFile;
}
if (!class_exists('BusinessDayService', false)) {
    throw new RuntimeException('BusinessDayService yüklenemedi. app/Core/BusinessDayService.php dosyasını kontrol edin.');
}
if(empty($_SESSION['admin_id']) && empty($_SESSION['cashier_id']) && (($_SESSION['staff_role']??'')!=='manager')) redirect('./');
$pdo=db(); BusinessDayService::install($pdo); $svc=business_day_service();$error='';$notice='';
try{
 if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$action=(string)($_POST['action']??'');
  if($action==='open'){require_permission('business_day.open');$svc->open((float)($_POST['opening_cash']??0),(string)($_POST['opening_note']??''),(string)($_POST['business_date']??''));$notice='Gün Başı tamamlandı. Satış işlemleri açıldı.';}
  if($action==='close'){require_permission('business_day.close');$svc->close((float)($_POST['counted_cash']??0),(string)($_POST['closing_note']??''),false);$notice='Gün Sonu tamamlandı. Satış işlemleri kilitlendi.';}
  if($action==='force_close'){require_permission('business_day.force_close');$svc->close((float)($_POST['counted_cash']??0),(string)($_POST['closing_note']??''),true,(string)($_POST['force_reason']??''));$notice='İş günü zorunlu olarak kapatıldı.';}
 }
}catch(Throwable $e){$error=$e->getMessage();}
$current=$svc->current();$checks=$current?$svc->checks((int)$current['id']):[];$summary=$current?$svc->summary((int)$current['id']):null;
$archive=$pdo->query("SELECT * FROM business_days ORDER BY id DESC LIMIT 30")->fetchAll();
$events=[];if($current){$q=$pdo->prepare('SELECT * FROM business_day_events WHERE business_day_id=? ORDER BY id DESC LIMIT 30');$q->execute([(int)$current['id']]);$events=$q->fetchAll();}
function bd_money(float $v):string{return number_format($v,2,',','.').' ₺';}
?><!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>İş Günü Merkezi · CherryHouse</title><link rel="stylesheet" href="assets/admin-premium.css?v=2800"><link rel="stylesheet" href="assets/business-day.css?v=2800"></head><body><main class="bd-shell"><header class="bd-header"><div><a href="./" class="bd-back">← Yönetim Paneli</a><h1>İş Günü Merkezi</h1><p>Takvim tarihinden bağımsız restoran operasyonu, kasa ve raporlama kontrolü.</p></div><div class="bd-state <?=$current?'open':'closed'?>"><span></span><?=$current?'İş Günü Açık':'İş Günü Kapalı'?></div></header>
<?php if($error):?><div class="bd-alert error"><?=e($error)?></div><?php endif;?><?php if($notice):?><div class="bd-alert ok"><?=e($notice)?></div><?php endif;?>
<?php if(!$current):?><section class="bd-open-card"><div class="bd-icon">☀️</div><h2>Satışa başlamak için Gün Başı yapın</h2><p>Gün Başı tamamlanmadan masa açılamaz, sipariş eklenemez ve ödeme alınamaz.</p><form method="post" class="bd-form"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="open"><label>İş günü tarihi<input type="date" name="business_date" value="<?=date('Y-m-d')?>" required></label><label>Açılış kasa tutarı<input type="number" name="opening_cash" min="0" step="0.01" value="0" required></label><label class="wide">Açılış / devir notu<textarea name="opening_note" rows="3" placeholder="Örn. Kasada 2.500 ₺ bozuk para bırakıldı."></textarea></label><button>Gün Başı Yap ve Satışı Aç</button></form></section>
<?php else:?>
<section class="bd-grid stats"><article><small>İş Günü</small><strong>#<?=e($current['business_no'])?></strong><span><?=e(date('d.m.Y',strtotime($current['business_date'])))?></span></article><article><small>Açılış</small><strong><?=e(date('H:i',strtotime($current['opened_at'])))?></strong><span><?=e($current['opened_by_name'])?></span></article><article><small>Toplam Tahsilat</small><strong><?=bd_money((float)$summary['total'])?></strong><span>İş günü bazlı</span></article><article><small>Beklenen Nakit</small><strong><?=bd_money((float)$summary['expected_cash'])?></strong><span>Açılış + nakit satış</span></article></section>
<section class="bd-grid main"><div class="bd-card"><div class="bd-card-head"><div><h2>Gün Sonu Kontrol Listesi</h2><p>Kritik kayıtlar tamamlanmadan normal kapanış yapılamaz.</p></div></div><div class="bd-checks"><?php foreach($checks as $c):?><div class="bd-check <?=$c['blocking']?'bad':'good'?>"><span><?=$c['blocking']?'!':'✓'?></span><div><b><?=e($c['label'])?></b><small><?=$c['blocking']?(int)$c['count'].' kayıt bekliyor':'Tamamlandı'?></small></div></div><?php endforeach;?></div><form method="post" class="bd-form close"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="close"><label>Sayılan kasa nakdi<input type="number" name="counted_cash" min="0" step="0.01" value="<?=e((string)$summary['expected_cash'])?>" required></label><label>Gün sonu / devir notu<textarea name="closing_note" rows="3" placeholder="Ertesi güne aktarılacak operasyon notu"></textarea></label><button <?=array_filter($checks,fn($c)=>$c['blocking'])?'disabled':''?>>Gün Sonunu Tamamla</button></form><?php if(has_permission('business_day.force_close') && array_filter($checks,fn($c)=>$c['blocking'])):?><details class="bd-force"><summary>Zorunlu kapanış seçenekleri</summary><form method="post" class="bd-form"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="force_close"><label>Sayılan kasa<input type="number" name="counted_cash" min="0" step="0.01" value="<?=e((string)$summary['expected_cash'])?>" required></label><label>Zorunlu kapanış nedeni<textarea name="force_reason" required></textarea></label><label>Kapanış notu<textarea name="closing_note"></textarea></label><button class="danger">Zorunlu Gün Sonu Yap</button></form></details><?php endif;?></div>
<div class="bd-card"><h2>İş Günü Olayları</h2><div class="bd-timeline"><?php foreach($events as $ev):?><div><time><?=e(date('H:i',strtotime($ev['created_at'])))?></time><span></span><p><b><?=e($ev['description'])?></b><small><?=e($ev['actor_name'])?></small></p></div><?php endforeach;?><?php if(!$events):?><p>Henüz olay kaydı bulunmuyor.</p><?php endif;?></div></div></section>
<?php endif;?>
<section class="bd-card archive"><h2>Son İş Günleri</h2><div class="bd-table"><table><thead><tr><th>No</th><th>İş Günü</th><th>Açılış</th><th>Kapanış</th><th>Durum</th><th>Kasa Farkı</th></tr></thead><tbody><?php foreach($archive as $d):?><tr><td>#<?=e($d['business_no'])?></td><td><?=e(date('d.m.Y',strtotime($d['business_date'])))?></td><td><?=e(date('d.m H:i',strtotime($d['opened_at'])))?></td><td><?=$d['closed_at']?e(date('d.m H:i',strtotime($d['closed_at']))):'—'?></td><td><span class="badge <?=e($d['status'])?>"><?=e($d['status']==='open'?'Açık':($d['status']==='forced_closed'?'Zorunlu kapalı':'Kapalı'))?></span></td><td><?=$d['cash_difference']!==null?bd_money((float)$d['cash_difference']):'—'?></td></tr><?php endforeach;?></tbody></table></div></section></main></body></html>