<?php
require __DIR__.'/_printer_bootstrap.php';
$pdo=db();$notice='';$error='';$edit=null;
try{
 if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$action=(string)($_POST['action']??'save');
  if($action==='save'){$id=(int)($_POST['id']??0);$name=trim((string)$_POST['name']);$station=trim((string)$_POST['station_name']);$type=(string)$_POST['connection_type'];if($name===''||$station==='')throw new RuntimeException('Yazıcı adı ve istasyon zorunludur.');if(!in_array($type,['network','browser','windows_share'],true))$type='browser';$isDefault=isset($_POST['is_default'])?1:0;
   if($isDefault)$pdo->exec('UPDATE kitchen_printers SET is_default=0');
   $vals=[$name,$station,$type,trim((string)($_POST['host']??'')),max(1,min(65535,(int)($_POST['port']??9100))),trim((string)($_POST['share_path']??'')),in_array((int)$_POST['paper_width'],[58,80],true)?(int)$_POST['paper_width']:80,$isDefault,isset($_POST['is_active'])?1:0];
   if($id){$pdo->prepare('UPDATE kitchen_printers SET name=?,station_name=?,connection_type=?,host=?,port=?,share_path=?,paper_width=?,is_default=?,is_active=? WHERE id=?')->execute([...$vals,$id]);}else{$pdo->prepare('INSERT INTO kitchen_printers(name,station_name,connection_type,host,port,share_path,paper_width,is_default,is_active) VALUES(?,?,?,?,?,?,?,?,?)')->execute($vals);}
   audit_log('printer_saved','Yazıcı kaydı güncellendi.',['printer_id'=>$id?:$pdo->lastInsertId()]);$notice='Yazıcı kaydedildi.';
  }elseif($action==='delete'){$id=(int)$_POST['id'];$q=$pdo->prepare('SELECT COUNT(*) FROM kitchen_print_jobs WHERE printer_id=?');$q->execute([$id]);if((int)$q->fetchColumn()>0){$pdo->prepare('UPDATE kitchen_printers SET is_active=0 WHERE id=?')->execute([$id]);$notice='Geçmiş baskıları bulunduğu için yazıcı silinmedi, pasif yapıldı.';}else{$pdo->prepare('DELETE FROM kitchen_print_rules WHERE printer_id=?')->execute([$id]);$pdo->prepare('DELETE FROM kitchen_printers WHERE id=?')->execute([$id]);$notice='Yazıcı silindi.';}
  }elseif($action==='test'){$job=KitchenPrinter::createTestJob((int)$_POST['id']);$notice='Test baskısı oluşturuldu. İş #'.$job;}
 }
}catch(Throwable $e){$error=$e->getMessage();}
if(isset($_GET['edit'])){$q=$pdo->prepare('SELECT * FROM kitchen_printers WHERE id=?');$q->execute([(int)$_GET['edit']]);$edit=$q->fetch();}
$printers=$pdo->query("SELECT p.*,(SELECT COUNT(*) FROM kitchen_print_jobs j WHERE j.printer_id=p.id AND j.status IN ('pending','failed')) waiting FROM kitchen_printers p ORDER BY p.is_default DESC,p.id")->fetchAll();
printer_page_start('Yazıcı Merkezi','printers');?>
<div class="head"><div><span class="eyebrow">KITCHEN PRINTER CENTER v5.1</span><h1>Yazıcı Merkezi</h1><p>Ağ, tarayıcı ve Windows köprü yazıcılarını istasyon bazında yönetin.</p></div><div class="actions"><a class="btn light" href="printer-rules.php">İletim Kuralları</a><a class="btn orange" href="print-queue.php">Baskı Kuyruğu</a></div></div>
<?php if($notice):?><div class="notice ok"><?=e($notice)?></div><?php endif;?><?php if($error):?><div class="notice err"><?=e($error)?></div><?php endif;?>
<div class="grid"><section class="card full"><h2><?=$edit?'Yazıcıyı Düzenle':'Yeni Yazıcı Ekle'?></h2><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="<?=e($edit['id']??0)?>"><div class="form-grid"><div><label>Yazıcı adı</label><input required name="name" value="<?=e($edit['name']??'')?>" placeholder="Ana Mutfak"></div><div><label>İstasyon adı</label><input required name="station_name" value="<?=e($edit['station_name']??'Ana Mutfak')?>"></div><div><label>Bağlantı tipi</label><select name="connection_type"><option value="network" <?=($edit['connection_type']??'')==='network'?'selected':''?>>Ağ / Ethernet (RAW 9100)</option><option value="browser" <?=($edit['connection_type']??'browser')==='browser'?'selected':''?>>Tarayıcıdan yazdır</option><option value="windows_share" <?=($edit['connection_type']??'')==='windows_share'?'selected':''?>>Windows paylaşımı / yerel köprü</option></select></div><div><label>Kâğıt genişliği</label><select name="paper_width"><option value="80" <?=($edit['paper_width']??80)==80?'selected':''?>>80 mm</option><option value="58" <?=($edit['paper_width']??80)==58?'selected':''?>>58 mm</option></select></div><div><label>IP / Host</label><input name="host" value="<?=e($edit['host']??'')?>" placeholder="192.168.1.20"></div><div><label>Port</label><input type="number" name="port" value="<?=e($edit['port']??9100)?>"></div><div class="full"><label>Windows paylaşım yolu</label><input name="share_path" value="<?=e($edit['share_path']??'')?>" placeholder="\\SERVER\\MUTFAK"></div><div><label><input style="width:auto" type="checkbox" name="is_default" <?=!empty($edit['is_default'])?'checked':''?>> Varsayılan yazıcı</label></div><div><label><input style="width:auto" type="checkbox" name="is_active" <?=!$edit||!empty($edit['is_active'])?'checked':''?>> Aktif</label></div></div><div class="actions" style="margin-top:16px"><button class="btn orange">Kaydet</button><?php if($edit):?><a class="btn light" href="printer-center.php">Vazgeç</a><?php endif;?></div></form></section></div>
<section class="card" style="margin-top:16px"><h2>Tanımlı Yazıcılar</h2><?php if(!$printers):?><div class="empty">Henüz yazıcı tanımlanmadı.</div><?php else:?><table><thead><tr><th>Yazıcı</th><th>Bağlantı</th><th>Durum</th><th>Bekleyen</th><th>İşlem</th></tr></thead><tbody><?php foreach($printers as $p):?><tr><td><strong><?=e($p['name'])?></strong><br><span class="muted"><?=e($p['station_name'])?> · <?=e($p['paper_width'])?> mm</span><?php if($p['is_default']):?> <span class="pill">Varsayılan</span><?php endif;?></td><td><?=e(['network'=>'Ağ','browser'=>'Tarayıcı','windows_share'=>'Windows Köprü'][$p['connection_type']]??$p['connection_type'])?><br><span class="muted"><?=e($p['connection_type']==='network'?($p['host'].':'.$p['port']):$p['share_path'])?></span></td><td><span class="pill <?=$p['is_active']?'ok':'bad'?>"><?=$p['is_active']?'Aktif':'Pasif'?></span></td><td><?=e($p['waiting'])?></td><td><div class="actions"><a class="btn light" href="?edit=<?=$p['id']?>">Düzenle</a><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="test"><input type="hidden" name="id" value="<?=$p['id']?>"><button class="btn">Test</button></form><form method="post" onsubmit="return confirm('Yazıcı kaldırılsın mı?')"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=$p['id']?>"><button class="btn danger">Sil</button></form></div></td></tr><?php endforeach;?></tbody></table><?php endif;?></section>
<?php printer_page_end();
