<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/bootstrap.php';
if(empty($_SESSION['admin_id'])) redirect('./');
$pdo=db();$notice='';$error='';
try{if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$values=[
'receipt_paper_width'=>in_array((string)($_POST['paper_width']??'80'),['58','80'],true)?(string)$_POST['paper_width']:'80',
'receipt_address'=>trim((string)($_POST['address']??'')),
'receipt_phone'=>trim((string)($_POST['phone']??'')),
'receipt_tax_info'=>trim((string)($_POST['tax_info']??'')),
'receipt_footer'=>trim((string)($_POST['footer']??'')),
'receipt_auto_print'=>isset($_POST['auto_print'])?'1':'0'];
$st=$pdo->prepare('INSERT INTO settings(setting_key,setting_value) VALUES(?,?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value)');foreach($values as $k=>$v)$st->execute([$k,$v]);$notice='Yazıcı ve fiş ayarları kaydedildi.';}}
catch(Throwable $e){$error=$e->getMessage();}
?><!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Fiş Ayarları</title><style>*{box-sizing:border-box}body{margin:0;background:#f3f4f6;font-family:system-ui;color:#111827}.top{background:#111827;color:#fff;padding:18px 28px;display:flex;justify-content:space-between}.top a{color:#fff}.wrap{max-width:850px;margin:28px auto;padding:0 18px}.card{background:#fff;border-radius:18px;padding:24px;box-shadow:0 10px 35px #0001}label{display:block;font-weight:700;margin:14px 0 6px}input,textarea,select{width:100%;padding:12px;border:1px solid #d1d5db;border-radius:10px;font:inherit}textarea{min-height:90px}.check{display:flex;align-items:center;gap:10px}.check input{width:auto}.btn{margin-top:20px;padding:13px 20px;border:0;border-radius:10px;background:#111827;color:#fff;font-weight:800}.ok,.err{padding:12px;border-radius:10px}.ok{background:#ecfdf5}.err{background:#fef2f2}</style><link rel="stylesheet" href="assets/admin-premium.css?v=310"></head><body><header class="top"><strong>Yazıcı ve Fiş Ayarları</strong><a href="./?page=dashboard">Yönetim Paneline Dön</a></header><main class="wrap"><section class="card"><?php if($notice):?><p class="ok"><?=e($notice)?></p><?php endif;?><?php if($error):?><p class="err"><?=e($error)?></p><?php endif;?><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><label>Termal kâğıt genişliği</label><select name="paper_width"><option value="80" <?=setting('receipt_paper_width','80')==='80'?'selected':''?>>80 mm</option><option value="58" <?=setting('receipt_paper_width','80')==='58'?'selected':''?>>58 mm</option></select><label>İşletme adresi</label><textarea name="address"><?=e(setting('receipt_address',''))?></textarea><label>Telefon</label><input name="phone" value="<?=e(setting('receipt_phone',''))?>"><label>Vergi / şirket bilgisi</label><input name="tax_info" value="<?=e(setting('receipt_tax_info',''))?>"><label>Fiş alt mesajı</label><textarea name="footer"><?=e(setting('receipt_footer','Afiyet olsun.'))?></textarea><label class="check"><input type="checkbox" name="auto_print" <?=setting('receipt_auto_print','0')==='1'?'checked':''?>> Fiş sayfası açıldığında yazdırma penceresini otomatik aç</label><button class="btn">Ayarları Kaydet</button></form></section></main><script src="assets/admin-premium.js?v=310"></script></body></html>
