<?php
require __DIR__.'/_printer_bootstrap.php';$pdo=db();$notice='';$error='';
try{if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$action=(string)$_POST['action'];if($action==='save'){$type=in_array($_POST['rule_type'],['product','category'],true)?$_POST['rule_type']:'category';$ref=(int)$_POST['reference_id'];$printer=(int)$_POST['printer_id'];if(!$ref||!$printer)throw new RuntimeException('Kategori/ürün ve yazıcı seçilmelidir.');$pdo->prepare("INSERT INTO kitchen_print_rules(rule_type,reference_id,printer_id,priority,is_active) VALUES(?,?,?,100,1) ON DUPLICATE KEY UPDATE printer_id=VALUES(printer_id),is_active=1")->execute([$type,$ref,$printer]);$notice='İletim kuralı kaydedildi.';}elseif($action==='delete'){$pdo->prepare('DELETE FROM kitchen_print_rules WHERE id=?')->execute([(int)$_POST['id']]);$notice='Kural silindi.';}}}catch(Throwable $e){$error=$e->getMessage();}
$printers=$pdo->query('SELECT id,name,station_name FROM kitchen_printers WHERE is_active=1 ORDER BY name')->fetchAll();$categories=$pdo->query('SELECT id,name FROM categories ORDER BY sort_order,id')->fetchAll();$products=$pdo->query('SELECT id,name FROM products WHERE is_active=1 ORDER BY name')->fetchAll();$rules=$pdo->query("SELECT r.*,p.name printer_name,CASE WHEN r.rule_type='category' THEN c.name ELSE pr.name END reference_name FROM kitchen_print_rules r JOIN kitchen_printers p ON p.id=r.printer_id LEFT JOIN categories c ON r.rule_type='category' AND c.id=r.reference_id LEFT JOIN products pr ON r.rule_type='product' AND pr.id=r.reference_id ORDER BY r.rule_type,r.id")->fetchAll();
printer_page_start('İletim Kuralları','rules');?>
<div class="head"><div><span class="eyebrow">AKILLI YÖNLENDİRME</span><h1>İletim Kuralları</h1><p>Ürün kuralı kategori kuralından; kategori kuralı varsayılan yazıcıdan önceliklidir.</p></div><a class="btn light" href="printer-center.php">Yazıcı Merkezi</a></div><?php if($notice):?><div class="notice ok"><?=e($notice)?></div><?php endif;?><?php if($error):?><div class="notice err"><?=e($error)?></div><?php endif;?>
<section class="card"><h2>Yeni Kural</h2><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="save"><div class="form-grid"><div><label>Kural tipi</label><select name="rule_type" id="ruleType"><option value="category">Kategori</option><option value="product">Ürün</option></select></div><div><label>Hedef yazıcı</label><select required name="printer_id"><option value="">Seçin</option><?php foreach($printers as $p):?><option value="<?=$p['id']?>"><?=e($p['name'].' · '.$p['station_name'])?></option><?php endforeach;?></select></div><div id="categorySelect"><label>Kategori</label><select name="reference_id"><?php foreach($categories as $c):?><option value="<?=$c['id']?>"><?=e($c['name'])?></option><?php endforeach;?></select></div><div id="productSelect" style="display:none"><label>Ürün</label><select disabled name="reference_id"><?php foreach($products as $p):?><option value="<?=$p['id']?>"><?=e($p['name'])?></option><?php endforeach;?></select></div></div><button class="btn orange" style="margin-top:16px">Kuralı Kaydet</button></form></section>
<section class="card" style="margin-top:16px"><h2>Aktif Kurallar</h2><?php if(!$rules):?><div class="empty">Henüz yönlendirme kuralı yok. Siparişler varsayılan yazıcıya gider.</div><?php else:?><table><thead><tr><th>Tip</th><th>Kategori / Ürün</th><th>Yazıcı</th><th></th></tr></thead><tbody><?php foreach($rules as $r):?><tr><td><span class="pill"><?=$r['rule_type']==='product'?'Ürün':'Kategori'?></span></td><td><strong><?=e($r['reference_name']??'Silinmiş kayıt')?></strong></td><td><?=e($r['printer_name'])?></td><td><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="btn danger">Sil</button></form></td></tr><?php endforeach;?></tbody></table><?php endif;?></section>
<script>const t=document.getElementById('ruleType'),c=document.getElementById('categorySelect'),p=document.getElementById('productSelect');t.addEventListener('change',()=>{const prod=t.value==='product';c.style.display=prod?'none':'';p.style.display=prod?'':'none';c.querySelector('select').disabled=prod;p.querySelector('select').disabled=!prod;});</script><?php printer_page_end();
