<?php
declare(strict_types=1);require __DIR__.'/bootstrap.php';
$notice='';$error='';$themes=QrThemeRegistry::all();
$sections=QrExperience::sections();$map=[];foreach($sections as $s)$map[$s['key']]=$s;
if($_SERVER['REQUEST_METHOD']==='POST'){
 try{verify_csrf();$allowed=array_keys($map);$order=[];foreach(explode(',',(string)($_POST['qr_section_order']??'')) as $k){$k=trim($k);if(in_array($k,$allowed,true)&&!in_array($k,$order,true))$order[]=$k;}foreach($allowed as $k)if(!in_array($k,$order,true))$order[]=$k;
 $v=[
 'qr_section_order'=>implode(',',$order),'qr_section_categories_enabled'=>'1','qr_menu_enabled'=>'1',
 'qr_theme'=>qrs_choice((string)($_POST['qr_theme']??'cherry'),array_keys($themes),'cherry'),'qr_accent_color'=>qrs_hex((string)($_POST['qr_accent_color']??''),'#8b1e2d'),'qr_ui_background'=>qrs_hex((string)($_POST['qr_ui_background']??''),'#f4efe6'),'qr_ui_surface'=>qrs_hex((string)($_POST['qr_ui_surface']??''),'#fffdf8'),'qr_ui_text'=>qrs_hex((string)($_POST['qr_ui_text']??''),'#191814'),'qr_ui_muted'=>qrs_hex((string)($_POST['qr_ui_muted']??''),'#716c63'),'qr_font_family'=>qrs_choice((string)($_POST['qr_font_family']??'inter'),['inter','manrope','poppins','playfair','cormorant','dm-sans'],'inter'),'qr_card_style'=>qrs_choice((string)($_POST['qr_card_style']??'elevated'),['elevated','bordered','flat','editorial'],'elevated'),'qr_card_radius'=>(string)max(0,min(36,(int)($_POST['qr_card_radius']??16))),
 'qr_show_hero'=>qrs_bool('qr_show_hero'),'qr_hero_title'=>trim((string)($_POST['qr_hero_title']??'')),'qr_hero_subtitle'=>trim((string)($_POST['qr_hero_subtitle']??'')),'qr_hero_image'=>trim((string)($_POST['qr_hero_image']??'')),'qr_logo_image'=>trim((string)($_POST['qr_logo_image']??'')),'qr_hero_height'=>(string)max(45,min(100,(int)($_POST['qr_hero_height']??78))),'qr_hero_overlay'=>(string)max(0,min(90,(int)($_POST['qr_hero_overlay']??35))),'qr_show_status'=>qrs_bool('qr_show_status'),'qr_show_readonly_note'=>qrs_bool('qr_show_readonly_note'),
 'qr_show_directory_intro'=>qrs_bool('qr_show_directory_intro'),'qr_directory_eyebrow'=>trim((string)($_POST['qr_directory_eyebrow']??'')),'qr_directory_title'=>trim((string)($_POST['qr_directory_title']??'')),'qr_directory_description'=>trim((string)($_POST['qr_directory_description']??'')),
 'qr_show_search'=>qrs_bool('qr_show_search'),'qr_ui_first_category_open'=>qrs_bool('qr_ui_first_category_open'),'qr_ui_single_category'=>qrs_bool('qr_ui_single_category'),'qr_ui_show_category_count'=>qrs_bool('qr_ui_show_category_count'),'qr_ui_show_category_numbers'=>qrs_bool('qr_ui_show_category_numbers'),'qr_ui_show_row_arrow'=>qrs_bool('qr_ui_show_row_arrow'),'qr_ui_show_product_images'=>qrs_bool('qr_ui_show_product_images'),'qr_ui_show_descriptions'=>qrs_bool('qr_ui_show_descriptions'),
 'qr_show_promo_bar'=>qrs_bool('qr_show_promo_bar'),'qr_promo_text'=>trim((string)($_POST['qr_promo_text']??'')),'qr_show_featured'=>qrs_bool('qr_show_featured'),'qr_feature_title'=>trim((string)($_POST['qr_feature_title']??'')),'qr_feature_text'=>trim((string)($_POST['qr_feature_text']??'')),
 'qr_show_info_box'=>qrs_bool('qr_show_info_box'),'qr_info_eyebrow'=>trim((string)($_POST['qr_info_eyebrow']??'')),'qr_info_title'=>trim((string)($_POST['qr_info_title']??'')),'qr_info_text'=>trim((string)($_POST['qr_info_text']??'')),
 'qr_show_chef_note'=>qrs_bool('qr_show_chef_note'),'qr_chef_note_title'=>trim((string)($_POST['qr_chef_note_title']??'')),'qr_chef_note_text'=>trim((string)($_POST['qr_chef_note_text']??'')),'qr_show_story'=>qrs_bool('qr_show_story'),'qr_story_title'=>trim((string)($_POST['qr_story_title']??'')),'qr_story_text'=>trim((string)($_POST['qr_story_text']??'')),'qr_show_social'=>qrs_bool('qr_show_social'),'qr_social_title'=>trim((string)($_POST['qr_social_title']??'')),'qr_social_text'=>trim((string)($_POST['qr_social_text']??'')),'qr_show_footer'=>qrs_bool('qr_show_footer'),'qr_price_note'=>trim((string)($_POST['qr_price_note']??''))];
 qrs_save($v);audit_log('qr_page_builder_published','QR Experience Studio 2.0 sayfa düzeni yayınlandı.',['sections'=>$order]);$notice='Sayfa düzeni kaydedildi ve canlı menüye yayınlandı.';
 }catch(Throwable $e){$error=$e->getMessage();}}
$order=QrExperience::sectionOrder();function ck(string $k,string $d='1'):string{return qrs_get($k,$d)==='1'?'checked':'';}
?><!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>QR Experience Studio 2.0</title><link rel="stylesheet" href="assets/studio2.css?v=3032"><link rel="stylesheet" href="assets/unified-admin.css?v=3040"><link rel="stylesheet" href="../assets/ch-media-library.css?v=3033"></head><body>
<div class="shell unified-qr-shell"><aside><a class="unified-brand" href="../enterprise/"><span>CH</span><div><b>Cherry House</b><small>Yönetim Merkezi</small></div></a><nav class="platform-nav"><a href="../enterprise/">⌂ Dashboard</a><a href="../enterprise/menu.php">▤ Menü Merkezi</a><a href="../enterprise/products.php">□ Ürünler</a><a href="../enterprise/categories.php">≡ Kategoriler</a><a href="../enterprise/media.php">▧ Medya Merkezi</a><a class="active-link" href="./">◈ QR Experience Studio</a></nav><div class="studio-nav-label">STUDIO ARAÇLARI</div><nav class="studio-tabs"><button class="active" data-tab="builder">Sayfa oluşturucu</button><button data-tab="design">Tasarım sistemi</button><button data-tab="content">İçerik ayarları</button></nav><div class="links"><a href="../enterprise/">← Yönetim Merkezi</a><a href="../../" target="_blank">Canlı menüyü aç ↗</a></div></aside>
<main><header><div><span>CHERRYHOUSE</span><h1>QR Experience Studio 2.0</h1><p>Bölümleri sırala, düzenle, anlık önizle ve tek düğmeyle yayınla.</p></div><b id="state">Canlı sürüm</b></header>
<?php if($notice):?><div class="alert ok"><?=qrs_e($notice)?></div><?php endif;?><?php if($error):?><div class="alert err"><?=qrs_e($error)?></div><?php endif;?>
<form method="post" id="studioForm"><input type="hidden" name="csrf" value="<?=qrs_e(csrf_token())?>"><input type="hidden" name="qr_section_order" id="sectionOrder" value="<?=qrs_e(implode(',',$order))?>">
<div class="work"><div class="editor">
<section class="pane active" data-pane="builder"><div class="section-title"><h2>Sayfa yapısı</h2><p>Tutamacı sürükleyerek bölümlerin canlı menüdeki sırasını değiştir.</p></div><div class="blocks" id="blocks">
<?php foreach($order as $i=>$key):$s=$map[$key];$default=in_array($key,['promo','featured','info','chef_note','story','social'],true)?'0':'1';?><article class="block" draggable="true" data-key="<?=qrs_e($key)?>"><button class="handle" type="button">☰</button><span class="num"><?=str_pad((string)($i+1),2,'0',STR_PAD_LEFT)?></span><div><b><?=qrs_e($s['label'])?></b><small><?=qrs_e($s['description'])?></small></div><label class="switch"><input type="checkbox" name="<?=['hero'=>'qr_show_hero','directory'=>'qr_show_directory_intro','search'=>'qr_show_search','categories'=>'qr_section_categories_enabled','promo'=>'qr_show_promo_bar','featured'=>'qr_show_featured','info'=>'qr_show_info_box','chef_note'=>'qr_show_chef_note','story'=>'qr_show_story','social'=>'qr_show_social','footer'=>'qr_show_footer'][$key]?>" <?=ck(['hero'=>'qr_show_hero','directory'=>'qr_show_directory_intro','search'=>'qr_show_search','categories'=>'qr_section_categories_enabled','promo'=>'qr_show_promo_bar','featured'=>'qr_show_featured','info'=>'qr_show_info_box','chef_note'=>'qr_show_chef_note','story'=>'qr_show_story','social'=>'qr_show_social','footer'=>'qr_show_footer'][$key],$default)?>><i></i></label><button class="edit" type="button" data-edit="<?=$key?>">Düzenle</button></article><?php endforeach;?></div></section>
<section class="pane" data-pane="design"><div class="section-title"><h2>Tasarım sistemi</h2><p>Tüm blokların ortak görünümünü yönet.</p></div><div class="panel"><h3>Tema</h3><div class="themes"><?php foreach($themes as $key=>$t):?><label><input type="radio" name="qr_theme" value="<?=qrs_e($key)?>" <?=qrs_get('qr_theme','cherry')===$key?'checked':''?>><b><?=qrs_e($t['name'])?></b><small><?=qrs_e($t['description'])?></small></label><?php endforeach;?></div></div><div class="grid"><div class="panel"><h3>Renkler</h3><?php foreach(['qr_ui_background'=>'Sayfa','qr_ui_surface'=>'Kart','qr_ui_text'=>'Ana yazı','qr_ui_muted'=>'İkincil yazı','qr_accent_color'=>'Vurgu'] as $k=>$l):?><label class="color"><input type="color" name="<?=$k?>" value="<?=qrs_e(qrs_get($k,['qr_ui_background'=>'#f4efe6','qr_ui_surface'=>'#fffdf8','qr_ui_text'=>'#191814','qr_ui_muted'=>'#716c63','qr_accent_color'=>'#8b1e2d'][$k]))?>"><span><?=$l?></span></label><?php endforeach;?></div><div class="panel"><h3>Tipografi ve kart</h3><label>Yazı tipi<select name="qr_font_family"><?php foreach(['inter'=>'Inter','manrope'=>'Manrope','poppins'=>'Poppins','playfair'=>'Playfair Display','cormorant'=>'Cormorant Garamond','dm-sans'=>'DM Sans'] as $v=>$l):?><option value="<?=$v?>" <?=qrs_get('qr_font_family','inter')===$v?'selected':''?>><?=$l?></option><?php endforeach;?></select></label><label>Kart biçimi<select name="qr_card_style"><?php foreach(['elevated'=>'Yükseltilmiş','bordered'=>'Çerçeveli','flat'=>'Düz','editorial'=>'Editoryal'] as $v=>$l):?><option value="<?=$v?>" <?=qrs_get('qr_card_style','elevated')===$v?'selected':''?>><?=$l?></option><?php endforeach;?></select></label><label>Köşe yuvarlaklığı <output><?=qrs_e(qrs_get('qr_card_radius','16'))?> px</output><input type="range" name="qr_card_radius" min="0" max="36" value="<?=qrs_e(qrs_get('qr_card_radius','16'))?>"></label></div></div></section>
<section class="pane" data-pane="content"><div class="section-title"><h2>İçerik ayarları</h2><p>Blokların metinlerini ve davranışlarını buradan düzenle.</p></div>
<div class="accordion">
<?php
$panels=[
'hero'=>['Hero',['qr_hero_title'=>'Başlık','qr_hero_subtitle'=>'Alt başlık','qr_hero_image'=>'Kapak görseli yolu','qr_logo_image'=>'Logo görseli yolu']],
'directory'=>['Menü Başlığı',['qr_directory_eyebrow'=>'Küçük üst başlık','qr_directory_title'=>'Ana başlık','qr_directory_description'=>'Açıklama']],
'promo'=>['Kampanya',['qr_promo_text'=>'Kampanya metni']],
'featured'=>['Öne Çıkan',['qr_feature_title'=>'Başlık','qr_feature_text'=>'Açıklama']],
'info'=>['Bilgi Kutusu',['qr_info_eyebrow'=>'Küçük başlık','qr_info_title'=>'Başlık','qr_info_text'=>'Bilgi metni']],
'chef_note'=>['Şef Notu',['qr_chef_note_title'=>'Başlık','qr_chef_note_text'=>'Metin']],
'story'=>['Hikâye',['qr_story_title'=>'Başlık','qr_story_text'=>'Metin']],
'social'=>['Sosyal Alan',['qr_social_title'=>'Başlık','qr_social_text'=>'Metin']],
'footer'=>['Footer',['qr_price_note'=>'Alt bilgi / fiyat notu']]];
$defs=['qr_hero_title'=>'İyi yemek, mutlu anlar.','qr_hero_subtitle'=>'Taze malzemelerle hazırlanmış lezzetleri keşfedin.','qr_directory_eyebrow'=>'MENÜMÜZ','qr_directory_title'=>'Bugün ne yemek istersiniz?','qr_directory_description'=>'Kategoriyi aç, ürünleri incele ve ayrıntılar için ürüne dokun.','qr_promo_text'=>'Bugüne özel fırsatları keşfet','qr_feature_title'=>'Günün öne çıkan lezzeti','qr_feature_text'=>'Öne çıkan lezzetlerimizi keşfet.','qr_info_eyebrow'=>'BİLGİ','qr_info_title'=>'Misafirlerimiz için','qr_info_text'=>'Wi-Fi ve çalışma saatleri için ekibimize danışabilirsiniz.','qr_chef_note_title'=>'Mevsimin en iyi ürünleriyle','qr_chef_note_text'=>'Mutfağımızda her tabak günlük ve özenle hazırlanır.','qr_story_title'=>'Sofrada başlayan bir hikâye','qr_story_text'=>'Lezzeti ve iyi malzemeyi merkeze alan bir mutfak.','qr_social_title'=>'Bizi Instagram’da takip et','qr_social_text'=>'Yeni ürünler ve duyurular için sosyal hesaplarımızdayız.','qr_price_note'=>'Fiyatlarımıza KDV dahildir.'];
foreach($panels as $id=>$p):?><details class="content-panel" data-editor="<?=$id?>"><summary><?=$p[0]?></summary><div><?php foreach($p[1] as $k=>$label):$long=str_contains($k,'text')||str_contains($k,'description')||$k==='qr_price_note';?><label><?=$label?><?php if($long):?><textarea name="<?=$k?>"><?=qrs_e(qrs_get($k,$defs[$k]??''))?></textarea><?php else:?><input name="<?=$k?>" value="<?=qrs_e(qrs_get($k,$defs[$k]??''))?>"><?php endif;?></label><?php endforeach;?><?php if($id==='hero'):?><div class="grid"><label>Yükseklik<input type="range" name="qr_hero_height" min="45" max="100" value="<?=qrs_e(qrs_get('qr_hero_height','78'))?>"></label><label>Karartma<input type="range" name="qr_hero_overlay" min="0" max="90" value="<?=qrs_e(qrs_get('qr_hero_overlay','35'))?>"></label></div><label class="check"><input type="checkbox" name="qr_show_status" <?=ck('qr_show_status')?> > Açık durumu</label><label class="check"><input type="checkbox" name="qr_show_readonly_note" <?=ck('qr_show_readonly_note')?> > Bilgilendirme notu</label><?php endif;?></div></details><?php endforeach;?>
<details class="content-panel"><summary>Kategori ve ürün davranışı</summary><div><?php foreach(['qr_ui_first_category_open'=>'İlk kategori açık','qr_ui_single_category'=>'Tek kategori açık','qr_ui_show_category_count'=>'Ürün sayısı','qr_ui_show_category_numbers'=>'Kategori numarası','qr_ui_show_row_arrow'=>'Detay oku','qr_ui_show_product_images'=>'Ürün görselleri','qr_ui_show_descriptions'=>'Ürün açıklamaları'] as $k=>$l):?><label class="check"><input type="checkbox" name="<?=$k?>" <?=ck($k,$k==='qr_ui_first_category_open'?'0':'1')?>> <?=$l?></label><?php endforeach;?></div></details>
</div></section></div>
<aside class="preview"><div class="preview-head"><div><b>Canlı önizleme</b><small>Kaydetmeden önce görün</small></div><button type="button" id="reload">↻</button></div><div class="phone"><iframe id="previewFrame" src="../../?preview=1"></iframe></div></aside></div>
<div class="save"><span id="dirtyText">Tüm değişiklikler canlı sürümle aynı.</span><button>Kaydet ve Yayınla</button></div></form></main></div><script src="assets/studio2.js?v=3032"></script><script src="../assets/ch-media-library.js?v=3033"></script></body></html>
