<?php
declare(strict_types=1);
require __DIR__.'/bootstrap.php';
ent_variant_install();
$pageTitle='Varyant Sistemi';$currentPage='variants';$pdo=ent_db();$error='';$notice=trim((string)($_GET['notice']??''));
try{
 if($_SERVER['REQUEST_METHOD']==='POST'){
  ent_verify_csrf();$action=(string)($_POST['action']??'');
  if($action==='save_group'){
   $id=(int)($_POST['id']??0);$name=trim((string)($_POST['name']??''));$desc=trim((string)($_POST['description']??''));
   $type=(string)($_POST['selection_type']??'single');$type=in_array($type,['single','multiple'],true)?$type:'single';
   $required=isset($_POST['is_required'])?1:0;$min=max(0,(int)($_POST['min_select']??0));$max=max(1,(int)($_POST['max_select']??1));
   if($type==='single'){$max=1;$min=$required?1:0;}elseif($max<$min){$max=$min;}
   if($name==='')throw new RuntimeException('Grup adı zorunludur.');
   if($id>0){$pdo->prepare('UPDATE variant_groups SET name=?,description=?,selection_type=?,is_required=?,min_select=?,max_select=?,updated_at=? WHERE id=?')->execute([$name,$desc,$type,$required,$min,$max,date('Y-m-d H:i:s'),$id]);}
   else{$sort=(int)$pdo->query('SELECT COALESCE(MAX(sort_order),0)+10 FROM variant_groups')->fetchColumn();$pdo->prepare('INSERT INTO variant_groups(name,description,selection_type,is_required,min_select,max_select,sort_order,is_active,created_at) VALUES(?,?,?,?,?,?,?,?,?)')->execute([$name,$desc,$type,$required,$min,$max,$sort,1,date('Y-m-d H:i:s')]);}
   ent_redirect('variants.php?notice='.rawurlencode('Varyant grubu kaydedildi.'));
  }
  if($action==='save_option'){
   $id=(int)($_POST['id']??0);$gid=(int)($_POST['group_id']??0);$name=trim((string)($_POST['name']??''));$delta=(float)str_replace(',','.',(string)($_POST['price_delta']??'0'));$default=isset($_POST['is_default'])?1:0;
   if($gid<1||$name==='')throw new RuntimeException('Grup ve seçenek adı zorunludur.');
   $pdo->beginTransaction();
   if($default){$pdo->prepare('UPDATE variant_options SET is_default=0 WHERE group_id=?')->execute([$gid]);}
   if($id>0){$pdo->prepare('UPDATE variant_options SET name=?,price_delta=?,is_default=?,updated_at=? WHERE id=? AND group_id=?')->execute([$name,$delta,$default,date('Y-m-d H:i:s'),$id,$gid]);}
   else{$sortStmt=$pdo->prepare('SELECT COALESCE(MAX(sort_order),0)+10 FROM variant_options WHERE group_id=?');$sortStmt->execute([$gid]);$pdo->prepare('INSERT INTO variant_options(group_id,name,price_delta,sort_order,is_default,is_active,created_at) VALUES(?,?,?,?,?,?,?)')->execute([$gid,$name,$delta,(int)$sortStmt->fetchColumn(),$default,1,date('Y-m-d H:i:s')]);}
   $pdo->commit();ent_redirect('variants.php?group='.$gid.'&notice='.rawurlencode('Seçenek kaydedildi.'));
  }
  if($action==='assign_products'){
   $gid=(int)($_POST['group_id']??0);$ids=array_values(array_unique(array_filter(array_map('intval',(array)($_POST['product_ids']??[])))));if($gid<1)throw new RuntimeException('Grup bulunamadı.');
   $pdo->beginTransaction();$pdo->prepare('DELETE FROM product_variant_groups WHERE group_id=?')->execute([$gid]);$ins=$pdo->prepare('INSERT INTO product_variant_groups(product_id,group_id,sort_order,created_at) VALUES(?,?,?,?)');foreach($ids as $i=>$pid)$ins->execute([$pid,$gid,($i+1)*10,date('Y-m-d H:i:s')]);$pdo->commit();
   ent_redirect('variants.php?group='.$gid.'&notice='.rawurlencode('Ürün atamaları güncellendi.'));
  }
  if($action==='toggle_group'){$pdo->prepare('UPDATE variant_groups SET is_active=1-is_active,updated_at=? WHERE id=?')->execute([date('Y-m-d H:i:s'),(int)($_POST['id']??0)]);ent_redirect('variants.php');}
  if($action==='delete_option'){$gid=(int)($_POST['group_id']??0);$pdo->prepare('DELETE FROM variant_options WHERE id=? AND group_id=?')->execute([(int)($_POST['id']??0),$gid]);ent_redirect('variants.php?group='.$gid);}
 }
}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$error=$e->getMessage();}
$groups=$pdo->query("SELECT g.*,(SELECT COUNT(*) FROM variant_options o WHERE o.group_id=g.id) option_count,(SELECT COUNT(*) FROM product_variant_groups pvg WHERE pvg.group_id=g.id) product_count FROM variant_groups g ORDER BY g.sort_order,g.id")->fetchAll(PDO::FETCH_ASSOC);
$selectedId=(int)($_GET['group']??($groups[0]['id']??0));$selected=null;foreach($groups as $g)if((int)$g['id']===$selectedId)$selected=$g;
$options=[];$assigned=[];if($selected){$st=$pdo->prepare('SELECT * FROM variant_options WHERE group_id=? ORDER BY sort_order,id');$st->execute([$selectedId]);$options=$st->fetchAll(PDO::FETCH_ASSOC);$st=$pdo->prepare('SELECT product_id FROM product_variant_groups WHERE group_id=?');$st->execute([$selectedId]);$assigned=array_map('intval',$st->fetchAll(PDO::FETCH_COLUMN));}
$products=$pdo->query('SELECT p.id,p.name,c.name category_name FROM products p LEFT JOIN categories c ON c.id=p.category_id ORDER BY c.sort_order,c.name,p.sort_order,p.name')->fetchAll(PDO::FETCH_ASSOC);
require __DIR__.'/_header.php';
?>
<section class="enterprise-hero compact-hero"><div><span>MENÜ ALTYAPISI</span><h2>Varyant gruplarını bir kez oluştur, tüm ürünlerde kullan.</h2><p>Boyut, pişirme derecesi, ekstra malzeme ve menü seçeneklerini QR ve POS için ortak veri modelinde yönet.</p></div><button class="primary-action" type="button" onclick="document.getElementById('newGroup').scrollIntoView({behavior:'smooth'})">+ Yeni Grup</button></section>
<?php if($notice):?><div class="ent-alert success"><?=ent_e($notice)?></div><?php endif;?><?php if($error):?><div class="ent-alert danger"><?=ent_e($error)?></div><?php endif;?>
<div class="variant-layout"><section class="enterprise-panel"><header><div><span>VARYANT GRUPLARI</span><h3><?=count($groups)?> grup</h3></div></header><div class="group-list"><?php foreach($groups as $g):?><a class="group-card <?=$selectedId===(int)$g['id']?'active':''?>" href="?group=<?=(int)$g['id']?>"><div><strong><?=ent_e($g['name'])?></strong><small><?=ent_e($g['selection_type']==='single'?'Tek seçim':'Çoklu seçim')?> · <?=(int)$g['option_count']?> seçenek · <?=(int)$g['product_count']?> ürün</small></div><span><?=$g['is_active']?'Aktif':'Pasif'?></span></a><?php endforeach;?><?php if(!$groups):?><div class="empty-state">Henüz varyant grubu yok.</div><?php endif;?></div></section>
<section class="enterprise-panel" id="newGroup"><header><div><span><?=$selected?'GRUBU DÜZENLE':'YENİ GRUP'?></span><h3><?=$selected?ent_e($selected['name']):'Varyant grubu oluştur'?></h3></div></header><form method="post" class="enterprise-form"><input type="hidden" name="csrf_token" value="<?=ent_e($_SESSION['csrf_token'])?>"><input type="hidden" name="action" value="save_group"><input type="hidden" name="id" value="<?=$selectedId?>"><label>Grup adı<input name="name" required value="<?=ent_e($selected['name']??'')?>" placeholder="Örn. Boyut"></label><label>Açıklama<textarea name="description" rows="2"><?=ent_e($selected['description']??'')?></textarea></label><div class="form-columns"><label>Seçim tipi<select name="selection_type"><option value="single" <?=($selected['selection_type']??'single')==='single'?'selected':''?>>Tek seçim</option><option value="multiple" <?=($selected['selection_type']??'')==='multiple'?'selected':''?>>Çoklu seçim</option></select></label><label>En fazla<input type="number" min="1" name="max_select" value="<?=(int)($selected['max_select']??1)?>"></label></div><label class="switch-row"><input type="checkbox" name="is_required" value="1" <?=!empty($selected['is_required'])?'checked':''?>><span>Seçim zorunlu</span></label><button class="primary-action">Kaydet</button></form></section></div>
<?php if($selected):?><div class="variant-layout lower"><section class="enterprise-panel"><header><div><span>SEÇENEKLER</span><h3><?=ent_e($selected['name'])?></h3></div></header><form method="post" class="option-form"><input type="hidden" name="csrf_token" value="<?=ent_e($_SESSION['csrf_token'])?>"><input type="hidden" name="action" value="save_option"><input type="hidden" name="group_id" value="<?=$selectedId?>"><input name="name" required placeholder="Seçenek adı"><input name="price_delta" inputmode="decimal" value="0" placeholder="Fiyat farkı"><label><input type="checkbox" name="is_default"> Varsayılan</label><button>Ekle</button></form><div class="option-list"><?php foreach($options as $o):?><div><span class="drag">☰</span><strong><?=ent_e($o['name'])?></strong><small><?=((float)$o['price_delta']>=0?'+':'').number_format((float)$o['price_delta'],2,',','.')?> ₺ <?=$o['is_default']?'· Varsayılan':''?></small><form method="post"><input type="hidden" name="csrf_token" value="<?=ent_e($_SESSION['csrf_token'])?>"><input type="hidden" name="action" value="delete_option"><input type="hidden" name="group_id" value="<?=$selectedId?>"><input type="hidden" name="id" value="<?=(int)$o['id']?>"><button class="danger-link">Sil</button></form></div><?php endforeach;?></div></section>
<section class="enterprise-panel"><header><div><span>ÜRÜNLERE ATA</span><h3><?=count($assigned)?> ürün seçili</h3></div></header><form method="post"><input type="hidden" name="csrf_token" value="<?=ent_e($_SESSION['csrf_token'])?>"><input type="hidden" name="action" value="assign_products"><input type="hidden" name="group_id" value="<?=$selectedId?>"><input class="product-search" type="search" placeholder="Ürün ara…" oninput="filterProducts(this.value)"><div class="product-checks" id="productChecks"><?php foreach($products as $p):?><label data-search="<?=ent_e(mb_strtolower($p['name'].' '.$p['category_name'],'UTF-8'))?>"><input type="checkbox" name="product_ids[]" value="<?=(int)$p['id']?>" <?=in_array((int)$p['id'],$assigned,true)?'checked':''?>><span><strong><?=ent_e($p['name'])?></strong><small><?=ent_e($p['category_name'])?></small></span></label><?php endforeach;?></div><button class="primary-action full">Atamaları Kaydet</button></form></section></div><?php endif;?>
<style>.compact-hero{min-height:auto}.variant-layout{display:grid;grid-template-columns:minmax(280px,.75fr) minmax(0,1.25fr);gap:18px;align-items:start;margin-top:18px}.variant-layout.lower{grid-template-columns:1fr 1fr}.group-list,.option-list{display:grid;gap:9px}.group-card{display:flex;justify-content:space-between;align-items:center;padding:14px;border:1px solid var(--ent-line);border-radius:14px;text-decoration:none;color:var(--ent-text);background:var(--ent-surface-2)}.group-card.active{outline:2px solid var(--ent-accent)}.group-card div{display:grid;gap:4px}.group-card small,.option-list small{color:var(--ent-muted)}.group-card>span{font-size:11px;font-weight:800}.enterprise-form{display:grid;gap:13px}.enterprise-form label{display:grid;gap:7px;font-weight:750}.enterprise-form input,.enterprise-form select,.enterprise-form textarea,.option-form input,.product-search{width:100%;padding:12px;border:1px solid var(--ent-line);border-radius:12px;background:var(--ent-surface-2);color:var(--ent-text);font:inherit}.form-columns{display:grid;grid-template-columns:1fr 1fr;gap:10px}.switch-row{display:flex!important;align-items:center}.switch-row input{width:auto}.option-form{display:grid;grid-template-columns:1.2fr .7fr auto auto;gap:8px;margin-bottom:14px;align-items:center}.option-form button,.danger-link{border:0;border-radius:10px;padding:10px 12px;cursor:pointer}.option-list>div{display:grid;grid-template-columns:auto 1fr auto auto;gap:10px;align-items:center;padding:12px;border-top:1px solid var(--ent-line)}.drag{cursor:grab}.danger-link{background:#ef444422;color:#f87171}.product-checks{display:grid;gap:7px;max-height:420px;overflow:auto;margin:12px 0}.product-checks label{display:flex;gap:10px;padding:11px;border:1px solid var(--ent-line);border-radius:12px}.product-checks span{display:grid}.product-checks small{color:var(--ent-muted)}.full{width:100%}.ent-alert{padding:13px 15px;border-radius:13px;margin:14px 0}.success{background:#16a34a22}.danger{background:#ef444422}@media(max-width:900px){.variant-layout,.variant-layout.lower{grid-template-columns:1fr}.option-form{grid-template-columns:1fr 1fr}.form-columns{grid-template-columns:1fr}}</style>
<script>function filterProducts(q){q=q.toLocaleLowerCase('tr');document.querySelectorAll('#productChecks label').forEach(el=>el.hidden=!el.dataset.search.includes(q));}</script>
<?php require __DIR__.'/_footer.php'; ?>
