<?php
declare(strict_types=1);
require __DIR__.'/bootstrap.php';
$pageTitle='Kategori Yönetimi';$currentPage='categories';$pdo=ent_db();$notice=trim((string)($_GET['notice']??''));$error='';
$cols=ent_columns('categories');$hasActive=in_array('is_active',$cols,true);$hasSort=in_array('sort_order',$cols,true);
try{if($_SERVER['REQUEST_METHOD']==='POST'){ent_verify_csrf();$action=(string)($_POST['action']??'');if($action==='save_category'){$id=(int)($_POST['id']??0);$name=trim((string)($_POST['name']??''));$description=trim((string)($_POST['description']??''));$sort=(int)($_POST['sort_order']??0);$active=isset($_POST['is_active'])?1:0;if($name==='')throw new RuntimeException('Kategori adı zorunludur.');$sets=['name=?','description=?'];$vals=[$name,$description];if($hasSort){$sets[]='sort_order=?';$vals[]=$sort;}if($hasActive){$sets[]='is_active=?';$vals[]=$active;}if($id>0){$vals[]=$id;$pdo->prepare('UPDATE categories SET '.implode(',',$sets).' WHERE id=?')->execute($vals);ent_redirect('categories.php?notice='.rawurlencode('Kategori güncellendi.'));}$fields=['name','description'];$vals=[$name,$description];if($hasSort){$fields[]='sort_order';$vals[]=$sort;}if($hasActive){$fields[]='is_active';$vals[]=$active;}$pdo->prepare('INSERT INTO categories('.implode(',',$fields).') VALUES('.implode(',',array_fill(0,count($fields),'?')).')')->execute($vals);ent_redirect('categories.php?notice='.rawurlencode('Kategori eklendi.'));}if($action==='toggle_category'&&$hasActive){$pdo->prepare('UPDATE categories SET is_active=IF(is_active=1,0,1) WHERE id=?')->execute([(int)$_POST['id']]);ent_redirect('categories.php?notice='.rawurlencode('Kategori durumu güncellendi.'));}}}catch(Throwable $e){$error=$e->getMessage();}
$editId=max(0,(int)($_GET['edit']??0));$edit=['id'=>0,'name'=>'','description'=>'','sort_order'=>0,'is_active'=>1];if($editId){$q=$pdo->prepare('SELECT * FROM categories WHERE id=?');$q->execute([$editId]);if($r=$q->fetch(PDO::FETCH_ASSOC))$edit=array_merge($edit,$r);}
$sql='SELECT c.*,COUNT(p.id) product_count FROM categories c LEFT JOIN products p ON p.category_id=c.id GROUP BY c.id ORDER BY '.($hasSort?'c.sort_order,':'').'c.id';$categories=$pdo->query($sql)->fetchAll(PDO::FETCH_ASSOC);
require __DIR__.'/_header.php';?>
<?php if($notice):?><div class="ent-alert success"><?=ent_e($notice)?></div><?php endif;?><?php if($error):?><div class="ent-alert danger"><?=ent_e($error)?></div><?php endif;?>
<section class="enterprise-hero compact-hero"><div><span>KATALOG YÖNETİMİ</span><h2>Kategorileri düzenleyin ve sıralayın.</h2><p>Bir kategori pasif olduğunda içindeki ürünler QR menüde gösterilmez.</p></div><div class="hero-actions"><a class="primary-action" href="products.php">Ürünleri Aç</a></div></section>
<div class="enterprise-grid catalog-layout"><section class="enterprise-panel catalog-form"><header><div><span><?=$editId?'DÜZENLE':'YENİ KAYIT'?></span><h3><?=$editId?'Kategoriyi düzenle':'Yeni kategori'?></h3></div><?php if($editId):?><a href="categories.php">İptal</a><?php endif;?></header><form method="post" class="enterprise-form"><input type="hidden" name="csrf_token" value="<?=ent_e($_SESSION['csrf_token'])?>"><input type="hidden" name="action" value="save_category"><input type="hidden" name="id" value="<?=(int)$edit['id']?>"><label>Kategori adı<input name="name" value="<?=ent_e($edit['name'])?>" required></label><label>Açıklama<textarea name="description" rows="4"><?=ent_e($edit['description'])?></textarea></label><?php if($hasSort):?><label>Sıralama<input type="number" name="sort_order" value="<?=(int)$edit['sort_order']?>"></label><?php endif;?><?php if($hasActive):?><label class="switch-row"><input type="checkbox" name="is_active" value="1" <?=!empty($edit['is_active'])?'checked':''?>><span>QR menüde aktif</span></label><?php endif;?><button class="primary-action"><?=$editId?'Değişiklikleri Kaydet':'Kategori Ekle'?></button></form></section>
<section class="enterprise-panel"><header><div><span>KATEGORİ LİSTESİ</span><h3><?=count($categories)?> kategori</h3></div></header><div class="category-list"><?php foreach($categories as $c):?><article><div class="category-order"><?=str_pad((string)(int)($c['sort_order']??0),2,'0',STR_PAD_LEFT)?></div><div><strong><?=ent_e($c['name'])?></strong><small><?=(int)$c['product_count']?> ürün<?=!empty($c['description'])?' · '.ent_e($c['description']):''?></small></div><span class="status-pill <?=(!$hasActive||!empty($c['is_active']))?'active':'passive'?>"><?=(!$hasActive||!empty($c['is_active']))?'Aktif':'Pasif'?></span><div class="row-actions"><a href="categories.php?edit=<?=(int)$c['id']?>">Düzenle</a><?php if($hasActive):?><form method="post"><input type="hidden" name="csrf_token" value="<?=ent_e($_SESSION['csrf_token'])?>"><input type="hidden" name="action" value="toggle_category"><input type="hidden" name="id" value="<?=(int)$c['id']?>"><button><?=!empty($c['is_active'])?'Pasifleştir':'Aktifleştir'?></button></form><?php endif;?></div></article><?php endforeach;?></div></section></div>
<style>.compact-hero{min-height:auto}.catalog-layout{grid-template-columns:minmax(290px,.7fr) minmax(0,1.5fr);align-items:start}.catalog-form{position:sticky;top:92px}.enterprise-form{display:grid;gap:14px}.enterprise-form label{display:grid;gap:7px;font-weight:750;font-size:13px}.enterprise-form input,.enterprise-form textarea{width:100%;border:1px solid var(--ent-line);background:var(--ent-surface-2);color:var(--ent-text);border-radius:12px;padding:12px 13px;font:inherit}.switch-row{display:flex!important;align-items:center}.switch-row input{width:auto}.category-list{display:grid}.category-list article{display:grid;grid-template-columns:44px minmax(0,1fr) auto auto;align-items:center;gap:13px;padding:14px 0;border-top:1px solid var(--ent-line)}.category-order{width:40px;height:40px;border-radius:12px;background:var(--ent-surface-2);display:grid;place-items:center;font-weight:900}.category-list article>div:nth-child(2){display:grid;gap:4px}.category-list small{color:var(--ent-muted)}.status-pill{padding:5px 8px;border-radius:999px;font-size:11px;font-weight:800}.status-pill.active{background:#16a34a22;color:#4ade80}.status-pill.passive{background:#ef444422;color:#f87171}.row-actions{display:flex;align-items:center;gap:8px}.row-actions a{color:var(--ent-accent);font-weight:800;text-decoration:none}.row-actions form{margin:0}.row-actions button{border:1px solid var(--ent-line);background:var(--ent-surface-2);color:var(--ent-text);border-radius:10px;padding:9px 12px}.ent-alert{padding:13px 15px;border-radius:13px;margin-bottom:14px}.ent-alert.success{background:#16a34a22;color:#4ade80}.ent-alert.danger{background:#ef444422;color:#f87171}@media(max-width:1050px){.catalog-layout{grid-template-columns:1fr}.catalog-form{position:static}}@media(max-width:700px){.category-list article{grid-template-columns:44px 1fr}.category-list .status-pill,.category-list .row-actions{grid-column:2}}</style>
<?php require __DIR__.'/_footer.php';?>
